### ISSUE TITLE
Controllers not visible following steps in greenscreen tutorial

### ISSUE THREAD

**Issue by michela** [stereolabs/zed-unity#1]
The Greenscreen VR tute doesn't work on 5.5/5.6 without an additional step.
https://www.stereolabs.com/documentation/guides/using-zed-with-unity/green-screen-vr.html

It seems now that SteamVR does not show the controllers by default. 

I got it working with 2 VIVE controllers with below:

Add the SteamVR [Camera Rig] to the root of the scene, 
Add Steam_VR_Update Poses script to
[CameraRig]/Camera(head)/Camera(eyes)
Delete MainCamera (as per default in new scene)

I also worked out that SteamVR device ids change after Play so you need to check what Controller (left) and Controller (right) are set to in script SteamVR_Tracked Object. Mine were set to Device 3 & 4 so took a while to work out why neither Device 1 or 2 were not working.

**Comment by F4r3n** [comment]
Hi,
Thanks for the feedback, the documentation has been updated.
