### ISSUE TITLE
Black screen after updating to ZED SDK 3.0.2 for zed mini

### ISSUE THREAD

**Issue by kaszim** [stereolabs/zed-unity#104]
After updating the ZED SDK and the unity plugins to the latest version none of the examples work. All binaries under "C:\Program Files (x86)\ZED SDK\samples\bin" works, as well as "C:\Program Files (x86)\ZED SDK\tools". There seems to be some issues with the updated unity plugin.

Everything worked fine under 2.8.

**Comment by kaszim** [comment]
The issue seems to be within the ZED_Forward_Lighting shader. Simply overwriting the current version with https://github.com/stereolabs/zed-unity/blob/c1c206b2e50e1440f730b2c0765fd4aac63eaf83/ZEDCamera/Assets/ZED/SDK/Helpers/Shaders/Lighting/ZED_Forward_Lighting.shader resolves the issue.

**Comment by obraun-sl** [comment]
Can you provide the Unity version you are using (2018.xx, or 2019.y) ?

**Comment by kaszim** [comment]
I am using Unity version 2019.3 under Windows, with an Oculus Rift S (if that makes any difference for shaders).

**Comment by kaszim** [comment]
Resolved by #106
