### ISSUE TITLE
ZED Unity svo recording while screen capturing

### ISSUE THREAD

**Issue by hankhhub** [stereolabs/zed-unity#108]
I realized only when using OBS studio to screen capture Unity editor in run time, if I tried to click the Start Recording button in ZED Manager, I get the error "Failed to start SVO Recording". Could this be a potential bug?

**Comment by giaplesg** [comment]
You should check the path that manager is trying to create the svo file at the ZED_Rig_Mono prefab. For example SVO File: Assets/Recording.svo if the ending (.svo) is missing or the Recording.svo already exist to the Assets folder then you should rename the SVO file like Recording1.svo
