### ISSUE TITLE
When build and run, failed. at AR Video Passthrough with Unity

### ISSUE THREAD

**Issue by mattun** [stereolabs/zed-unity#114]
I tried https://www.stereolabs.com/docs/unity/video-passthrough/ , this tutorial with Oculus rift s and ZED 2.
When just play, good, but after install XR plugins, then build and run , failed.

Unity said 
"Assets\ZED\SDK\NativeInterface\ZEDCamera.cs(263,26): error CS0103: The name 'ZEDLayersManager' does not exist in the current context"

I checked ZEDLayersManager.cs

"This class creates automaticaly layers on load"

So, unity couldn't load by auto?

**Comment by Bvallon-sl** [comment]
Hi, Did you try closing Unity et reopen it ? The layers should be created when Unity loads or when scripts are recompiled. You can check if "arLayer" and "tagInvisibleToZED" are created in Project Settings -> Tags and Layers.

**Comment by mattun** [comment]
Thanks I will check it.

**Comment by Bvallon-sl** [comment]
Hi,  #117 is resolving this issue.
