### ISSUE TITLE
Second ZEDManager instantiated at runtime failes to create camera

### ISSUE THREAD

**Issue by thedevleon** [stereolabs/zed-unity#115]
Long story short, I'm creating a second ZEDManager at runtime to read from an SVO file, setting it up as follows:

```
        var virtualZedGO = new GameObject("VirtualZED");
        virtualZedGO.transform.SetParent(this.transform);
        virtualZedGO.SetActive(false);
        virtualZED = virtualZedGO.AddComponent<ZEDManager>();
        virtualZED.cameraID = ZED_CAMERA_ID.CAMERA_ID_02;
        virtualZED.inputType = INPUT_TYPE.INPUT_TYPE_SVO;
        virtualZED.enableTracking = false;
        virtualZED.enableSpatialMemory = false;
        virtualZED.svoInputFileName = currentRecording.SVOFileName;
        virtualZED.svoRealTimeMode = true;
        virtualZED.svoLoopBack = true;
        virtualZED.pauseSVOReading = false;
        virtualZedGO.SetActive(true);
```

However, this fails and gives me an error:
`ZEDManager on VirtualZED couldn't connect to camera: CAMERA_ID_02. Check if another ZEDManager is already connected.`

I also have a ZED_Rig_Stereo with Camera_ID 1 in the scene that is enabled from the start, that connects to my ZED Mini attached to my Valve Index just fine.

I'm using SDK version 2.8.5b and the Unity plugin v2.8.3,

**To Reproduce**:
- Add two ZEDManagers in a scene. 
- One has USB as the input type and has Camera_ID 1
- The other one uses a SVO and has Camera_ID 2
- Enable both and run the scene: All works fine.
- Disable one, run the scene and then enable it: You will get the error above.
- It doesn't matter which one is disabled and which one is enabled from the start, the one that is enabled later and not at the same time as the first one will always fail with the error above.

Attached is an example scene, as well as the SL_unityWrapper_Log, if that helps.

[TestScene.zip](https://github.com/stereolabs/zed-unity/files/4272023/TestScene.zip)
[SL_unityWrapper_Log.txt](https://github.com/stereolabs/zed-unity/files/4272028/SL_unityWrapper_Log.txt)

Edit:
- The issue is still present with SDK v3.0.3 and the latest master commit of the unity plugin.
- The error only happens if the second ZEDManager is enabled after the first one is fully initialized (after loading modules, and when the image is first rendered in the ZED_Rig_Stereo). If the second ZEDManager is enabled during the loading process of the first, it will work fine.

**Comment by thedevleon** [comment]
Another issue I found:

When real-time mode is enabled on the second ZEDManager, it starts lagging immensively as soon as the first ZEDManager (ZED_Rig_Stereo) is fully initialized, and even though looping is enabled, the ZEDManager stops playback at some point.

Here's an video that shows the issue.
Notice that while, and before the ZED_Rig_Stereo has fully loaded, playback of the second ZEDManager (visualized with a PointCloud) is smooth. As soon as the first ZEDManager (ZED_Rig_Stereo) has initialized, playback starts lagging, and ultimatively, stops.

https://youtu.be/QMEa9shio_Q

**Comment by zawazawagh** [comment]
Having the same problem with  SDK version 3.4 & Unity plugin version 3.4
