### ISSUE TITLE
No way to render stereo to custom hmd when stereo rig is present

### ISSUE THREAD

**Issue by TheBricktop** [stereolabs/zed-unity#12]
We are trying to create custom stereo rig for zed camera with hmd working as a second monitor, we need to render stereo side by side on desktop, while original zed stereo rig is present on the scene it overrides all other cameras making us unable to render stereoscopic image. (all is black but Cameras object indicates that tracking is working allright)
unity 2017.3

**Comment by jtoump** [comment]
+1
