### ISSUE TITLE
ZED_HDRP Does not remove itself automatically when changing render pipelines.

### ISSUE THREAD

**Issue by CosmicBen** [stereolabs/zed-unity#125]
In the _ZEDDefineHandler.cs_ file (lines 123 and 124) the "**ZED_HDRP**" preprocessor definition is created when the hdrp package is found. When the package is not found the "**ZED_HDR{**" preprocessor definition is removed.

This is a minor bug since most people will not be changing render pipelines frequently but is best fixed early.

**Comment by Bvallon-sl** [comment]
Hi, Thanks for reporting !
