### ISSUE TITLE
real-time texture 

### ISSUE THREAD

**Issue by CChun1** [stereolabs/zed-unity#133]
When doing spatial mapping with ZED mini, we can only see the chunks updated in real-time. Is it possible to see real-time textures mapping? Any suggestions would be wonderful!

**Comment by Vertigo-VR** [comment]
Hello CChun1

I do not believe this is possible - I am not from Stereolabs so take this with a grain of salt. Here is some alternative solutions:
1 - Divide your scans into smaller segments (perhaps a few minutes) to apply the texture often.
2 - Mapping in the point cloud format lets you see the colors of the scan instantly. This feature is not available in the current Unity-plugin, but I have been told it will be coming in plugin v 3.2.0.
