### ISSUE TITLE
The ZED plugin cannot be loaded

### ISSUE THREAD

**Issue by mrbingo41** [stereolabs/zed-unity#134]
Looks like the latest 3.2 SDK is not recognized by the latest Unity plugin.
The release archive website is down so there is no way to get 3.1 SDK.

**Comment by jernejp21** [comment]
- Download ZED SDK 3.1 from [here](https://www.stereolabs.com/developers/release/3.1/)
- Download ZED Unity plugin 3.1 from [here](https://github.com/stereolabs/zed-unity/releases)

I did this last week and it worked for me. Before installing ZED SDK on Windows, remove all other versions.

**Comment by mrbingo41** [comment]
Their server with older SDKs is down, this link doesn't work
https://stereolabs.sfo2.cdn.digitaloceanspaces.com/zedsdk/3.1/ZED_SDK_Windows10_cuda10.2_v3.1.2.exe

Can you share the exe file you downloaded somehow? Thanks.

**Comment by jernejp21** [comment]
Try this link. This is for CUDA 10.2. 
[https://download.stereolabs.com/zedsdk/3.1/cu102/win](https://download.stereolabs.com/zedsdk/3.1/cu102/win)

This is for CUDA 10. 
[https://download.stereolabs.com/zedsdk/3.1/cu100/win](https://download.stereolabs.com/zedsdk/3.1/cu100/win)

**Comment by mrbingo41** [comment]
It leads to the same broken url.

**Comment by ckorris** [comment]
I just tried now (2 days later) and the links work for me. Can you try again?

**Comment by mrbingo41** [comment]
Works now, thank you.

**Comment by obraun-sl** [comment]
Note that the ZED SDK 3.2 is compatible with the staging_3.2 branch here : 
https://github.com/stereolabs/zed-unity/tree/staging_3.2
