### ISSUE TITLE
ZED 2 + unityy

### ISSUE THREAD

**Issue by HyperLethalVector** [stereolabs/zed-unity#135]
Hi there!

I just bought a ZED 2, and downloaded the newest SDK for unity in preparation for it,

However, I now realized that the 3.2 sdk is not compatible with the latest unity packages.

1) is Zed 2 compatible with the 3.1 sdk?
2) if not, Will there be plans to support it with the unity plugin? or should I cancel my order now :(

**Comment by obraun-sl** [comment]
You can use the staging_3.2 branch for compatibility with ZED SDK 3.2. (https://github.com/stereolabs/zed-unity/tree/staging_3.2)
(and ZED2 is supported since 3.0)
