### ISSUE TITLE
ZED 3.2 Unity Package + OpenCV package

### ISSUE THREAD

**Issue by masterchop** [stereolabs/zed-unity#137]
For some reason if i import the OpenCV  for unity (2.2.8) on a project with the ZED 3.2 package all ZED scripts for OpenCV complain about the missing references for OpenCV and everything breaks, am i missing any steps that i havent seen in any of the instructions.

I get errors like this:

`Assets\ZED\Examples\OpenCV ArUco Detection\Scripts\Core\MarkerObject.cs(6,22): error CS0234: The type or namespace name 'CoreModule' does not exist in the namespace 'OpenCVForUnity' (are you missing an assembly reference?)`

for pretty much any OpenCV reference, all the openCV examples worked no problem. its just the Zed ones.

Update #1 
I updated all OpenCV references in ZED scripts to:

using OpenCVforUnity;
THat solved the problem but the following error persist:

        DICT_APRILTAG_16h5 = Aruco.DICT_APRILTAG_16h5,
        DICT_APRILTAG_25h9 = Aruco.DICT_APRILTAG_25h9,
        DICT_APRILTAG_36h10 = Aruco.DICT_APRILTAG_36h10,
        DICT_APRILTAG_36h11 = Aruco.DICT_APRILTAG_36h11

those tags are consider invalid. Any reason for that? Also the Example scenes dont work.
I am able to use aruco sample screen from Opencv package with the ZED camera but not the Zed package with the Zed Camera.

Also the line 112 from ZEDArUcoDetectionMananager.cs requires an extra parameter:

`Aruco.detectMarkers(iamgeMat, predict, corners, ids, detectparams, rejectedpoints, camMat);`

its missing the distCoeff Mat

Update #2, the distcoeff is 0 as the images are already corrected.

**Comment by Pappol** [comment]
I am having the same issue how did u solve it?
