### ISSUE TITLE
Standalone plugin for C#

### ISSUE THREAD

**Issue by MiaoDX** [stereolabs/zed-unity#14]
Dear devs,

Hi, thanks a lot for the various SDKs for the zed camera, I have used python/C++ SDK in my projects, and now, I am wondering if there are any plans for a standalone C# SDK instead of relaying the *heavy* unity3d as dependence?

Looking forward to your reply.

**Comment by tomitrescak** [comment]
I am wondering the same. I tried to import the "sl_unitywrapper.dll" and "sl_mr_core.dll" into my project but no luck. Would you be able to provide wrappers for C# projects? For example to use it with EMGU.CV?

**Comment by MiaoDX** [comment]
This seems to be somewhat solved (at least for me), please see [https://github.com/stereolabs/zed-unity/issues/15](https://github.com/stereolabs/zed-unity/issues/15) if you also need this, that is not the official version, but the codes pruned by @tomitrescak  is pretty good to use, I also pushed my local version to the github: [https://github.com/MiaoDX/ZED_EmguCV](https://github.com/MiaoDX/ZED_EmguCV), I removed the `async` codes to be more friendly to VS2010 (which is somewhat historical issue of my ongoing project). 

And thanks for @tomitrescak  !
