### ISSUE TITLE
ZED unity is not compatible with XR plugin management

### ISSUE THREAD

**Issue by daniel-halodi** [stereolabs/zed-unity#144]
None of the VR functions work correctly due to being made for the XR device system in unity that obsolete and deprecated from unity 2020.1, and is replaced by the XR plugin management system, rendering it unusable.

**Comment by DrFritzi** [comment]
Any news on this? The ZED Unity SDK is the only package blocking us from updating to the newer Unity versions.

**Comment by Bvallon-sl** [comment]
Hi,

Sorry for the late reply.

You can take a look at the new branch called "[xr_compatibility_3.5]"(https://github.com/stereolabs/zed-unity/tree/xr_compatibility_3.5). It is now compatible with newer Unity versions and the new XR plugin management.
For the moment it keeps backward compatibility with the old system and we tried to duplicate the least amount of code possible  so it does not use that much of the new API (to avoid breaking everything for Unity2018 users).

We will wait for your feedbacks before merging into the master branch.

Best regards,
Benjamin V.
