### ISSUE TITLE
Example scenes don't render properly on the HTC VIVE PRO EYE

### ISSUE THREAD

**Issue by rush17m** [stereolabs/zed-unity#146]
While trying out the example scenes that use the ZED stereo Rig so that the background is also visible, like the Planetarium example, the rendering on the headset is wrong. The video stream is completely distorted because of a bad overlap between the images from the left and right eye. 
Any idea how to fix this?
The example executes perfectly fine if you're not rendering it on the VR headset.
To execute it on the VR headset, I simply from the SteamVR CameraRig into the scene.

**Comment by Bvallon-sl** [comment]
Hi, the planetarium example scene is working by it-self as you don't need to add anything to make it work.
To know more about the Unity plugin, please take a look at the documentation/tutorials available on our website. 
You can find it here : https://www.stereolabs.com/docs/unity/
