### ISSUE TITLE
Object Detection make CPU overload

### ISSUE THREAD

**Issue by nguyenanhtien2606** [stereolabs/zed-unity#149]
Hi,
I need to use object detection for my project, I have updated to latest SDK (version 3.3.0). But all four detect mode are causing my CPU to overload (details in the image below).

My system info:
CPU: Intel Core I9-9900K
RAM: 16GB
GPU: GTX 1060 3GB

I just run default scene demo Object detection of ZED SDK. How I can fix it?

![Screenshot 2020-11-06 100115](https://user-images.githubusercontent.com/44779836/98322362-ccf7df80-2019-11eb-9d4a-fc8cad6d284b.png)
![Screenshot 2020-11-06 100149](https://user-images.githubusercontent.com/44779836/98322364-cff2d000-2019-11eb-81a5-92a9d4bdad4a.png)
![Screenshot 2020-11-06 100218](https://user-images.githubusercontent.com/44779836/98322366-d1bc9380-2019-11eb-9a1f-34ddaaba03c4.png)

**Comment by nguyenanhtien2606** [comment]
UPDATE!
I also test it in another strong hardware:
CPU: Ryzen 9 3900X
RAM: 32GB
GPU: GTX 1080 8GB

And I got the same result: 99-100% CPU for object detection.
Any solution for this?

**Comment by Bvallon-sl** [comment]
Hi,

Sorry for the inconvenience. We are looking into it at the moment.

Best regards

**Comment by Bvallon-sl** [comment]
Hi,

We've found the issue. It's coming from the version of opencv we used for the multithreading in OD/SK when the Object tracking option is enabled. It is not hardware related at all.

It will be fixed with the 3.4 release of the SDK.

The only workaround I can give you is to use the version 3.2.2 instead.

Best regards

**Comment by nguyenanhtien2606** [comment]
> Hi,
> 
> We've found the issue. It's coming from the version of opencv we used for the multithreading in OD/SK when the Object tracking option is enabled. It is not hardware related at all.
> 
> It will be fixed with the 3.4 release of the SDK.
> 
> The only workaround I can give you is to use the version 3.2.2 instead.
> 
> Best regards

Hi,
Thanks for your answer. I'm using version 3.2.2, this version don't make overload when use "MULTI_CLASS_BOX" model. But "HUMAN_BODY" models still have this error. Hope it will be fixed soon.

Many thanks!

**Comment by Bvallon-sl** [comment]
Hi,

We have release a 3.3.2 version of the ZED SDK that is fixing the CPU usage issue.
You can download it [here](https://www.stereolabs.com/developers/release/).

Best regards.

**Comment by nguyenanhtien2606** [comment]
> Hi,
> 
> We have release a 3.3.2 version of the ZED SDK that is fixing the CPU usage issue.
> You can download it [here](https://www.stereolabs.com/developers/release/).
> 
> Best regards.

Thanks for new version! It works very well.
