### ISSUE TITLE
zedCamera.RetrieveTextures() on MainThread

### ISSUE THREAD

**Issue by falichs** [stereolabs/zed-unity#153]
Currently the function zedCamera.RetrieveTextures() is called by unitys' main thread (in ZEDManager.UpdateImages() ). 
zedCamera.RetrieveTextures() seems to be a blocking call and takes quite a long time to return (I measured ~5.5ms on average).

I'd suggest moving zedCamera.RetrieveTextures() to the ThreadedZEDGrab Thread, right after zedCamera.Grab returns success:

```
public void UpdateImages()
...
if (newFrameAvailable) //ThreadedZEDGrab()/AcquireImages() grabbed images we haven't updated yet. 
        {
            lock (zedCamera.grabLock)
            {
                // move RetrieveTextures() to ThreadedZEDGrab
                // zedCamera.RetrieveTextures(); //Tell the wrapper to compute the textures. 
                zedCamera.UpdateTextures(); //Tell the wrapper to update the textures. 
                imageTimeStamp = zedCamera.GetImagesTimeStamp();
            }

            //For external module ... Trigger the capture done event.
            if (OnGrab != null)
                OnGrab();
            ...
```

```
private void AcquireImages()
    {
        if (requestNewFrame && zedReady)
        {
            sl.ERROR_CODE e = sl.ERROR_CODE.FAILURE;
            if (inputType == sl.INPUT_TYPE.INPUT_TYPE_SVO)
            {
                //handle pause
                ...
            }
            else if (!pauseLiveReading)
            {
                e = zedCamera.Grab(ref runtimeParameters);
            }

            lock (zedCamera.grabLock)
            {
                ...
                else if (e == sl.ERROR_CODE.SUCCESS)
                {
                    // Move blocking RetrieveTextures here
                    zedCamera.RetrieveTextures();
                    ...
```

I gave it a try and i'm gaining a noticeable amount of perfomance. 
I couldn't find any side-effects so far ;) What do you think?
Am I missing something?

**Comment by stevenjj** [comment]
Hey @falichs, 
I'm not with the ZED developers, but on a similar project we tried retrieving and processing textures (not necessarily with the ZED)on a separate thread. While there is a performance increase, this approach de-syncs with the rest of Unity's render pipeline. It's not clear what's happening under the hood but some of the user experience can be degraded if certain Unity elements are slower with respect to others. We ultimately had to abandon processing textures on a separate thread.
