### ISSUE TITLE
Missing Entry Point in sl_unitywrapper

### ISSUE THREAD

**Issue by falichs** [stereolabs/zed-unity#158]
Hi there,
i'd love to use the region-based automatic Gain/Exposure Mode on the ZED Mini. 

Unfortunately it seems to me that `[DllImport(nameDll, EntryPoint = "dllz_get_roi_for_aec_agc")]` from **ZEDCamera.cs** points to nowhere.
I'm using [DLL Export Viewer](https://www.nirsoft.net/utils/dll_export_viewer.html) to inspect the **sl_unitywrapper.dll** and it seems like the entry point is indeed missing.

Will this feature be added soon? 
It seems like the main ZED SDK [already supports](https://www.stereolabs.com/docs/api/classsl_1_1Camera.html#aa266794188e5b07018a6252fb5f5d78e) it.

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for reaching us out.
Indeed the function was missing in the dll.
It will be added in the 3.4 release of the plugin, which will be available soon.

Best regards,
BV

**Comment by Bvallon-sl** [comment]
Hi again,

The 3.4 release is now available (https://github.com/stereolabs/zed-unity).
Can you confirm that the feature is now working correctly ?

Thanks for you help.

Best regards,
BV

**Comment by falichs** [comment]
Thank you so much for the quick response!

I'm still in the process of upgrading my project to v3.4

once i'm done i will let you know if it works

**Comment by falichs** [comment]
Thanks! It works!
