### ISSUE TITLE
X, Y, Z-axes are converting every frame, when I use "ZED_Rig_mono" and "ZED_Rig_stereo".

### ISSUE THREAD

**Issue by YuyaMurai** [stereolabs/zed-unity#163]
X, Y, Z-axes are converting every frame, when I use "ZED_Rig_mono" and "ZED_Rig_stereo".
How can I fix it?
![スクリーンショット 2021-02-03 162918](https://user-images.githubusercontent.com/73993194/106712949-0c47c380-663d-11eb-982d-ea7ba582db79.png)
![スクリーンショット 2021-02-03 162937](https://user-images.githubusercontent.com/73993194/106712954-0d78f080-663d-11eb-8239-794771f3939e.png)

**Comment by obraun-sl** [comment]
Note : Same issue/cause than https://github.com/stereolabs/zed-unity/issues/162
