### ISSUE TITLE
Obsolete API usage for Unity 2020.3.4f1

### ISSUE THREAD

**Issue by AustinSmith13** [stereolabs/zed-unity#175]
**ZEDManager.cs** and **ZEDMixedRealityPlugin.cs**

**XRDevice.isPresent** and **XRDevice.model** can be found in both of those files above but are currently either missing or obsolete.

Can we add a version ifdef check to use Unity's new **XRDisplaySubsystem**?

I also do not see any support for Unity's new XR Management Plugin is this currently something in the works?

**Comment by Bvallon-sl** [comment]
Hi,

As you said, the Unity plugin is not yet compatible with the new XR plugin from Unity.
We plan to make it compatible in a near future. However I can not give you any release date for the moment.

Best regards,
Benjamin V.
