### ISSUE TITLE
Unity crashes while AI model is generated!

### ISSUE THREAD

**Issue by bastidererste** [stereolabs/zed-unity#180]
i got the unity plugin running with the help of #124 

When i start the body-traking example unity crashes after 10 seconds and i get this error in the editor log:

[ZED][Object Detection] Please wait while the AI model is being optimized for your graphics card
 This operation will be run only once and may take a few minutes   |/-\|/-\|/-\|/-\|/-\|-Stacktrace:

at <unknown> <0xffffffff>
  at (wrapper managed-to-native) sl.ZEDCamera.dllz_enable_objects_detection (int,sl.dll_ObjectDetectionParameters&) [0x0009e] in <13008acc88dc42ddb5b2364ab22986f6>:0
  at sl.ZEDCamera.EnableObjectsDetection (sl.dll_ObjectDetectionParameters&) [0x00013] in C:\Users\production\Desktop\parsec-sdk-master\examples\ZED_new\Assets\ZED\SDK\NativeInterface\ZEDCamera.cs:2633
  at ZEDManager/<startObjectDetection>d__313.MoveNext () [0x00232] in C:\Users\production\Desktop\parsec-sdk-master\examples\ZED_new\Assets\ZED\SDK\Helpers\Scripts\ZEDManager.cs:2734
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator,intptr) [0x00027] in <c7864a0eaeb24b2a999fb177623d54b4>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object_intptr (object,intptr,intptr,intptr) [0x00027] in <c7864a0eaeb24b2a999fb177623d54b4>:0

Unity 2020.3.7f1
SDK 3.5
ZED2

**Comment by bastidererste** [comment]
thx for lookin in to this!

the binary ZED_Object_detection_birds_eye_viewer.exe doesn't run either... heres the output:

C:\Program Files (x86)\ZED SDK\samples\bin>ZED_Object_detection_birds_eye_viewer.exe
[ZED][Init] Depth mode: ULTRA
[ZED][Init] Video mode: HD1080@30
[Sample] Object Detection: Loading Module...

[ZED][Object Detection] Please wait while the AI model is being optimized for your graphics card
 This operation will be run only once and may take a few minutes  -
C:\Program Files (x86)\ZED SDK\samples\bin>

**Comment by bastidererste** [comment]
i also ran the python version, and it works

**Comment by Bvallon-sl** [comment]
Hi,

Can you try different Detection model (Multi_class_box, Multi_class_box_accurate ..) to see if they are all causing a crash ?

Thanks for your feedbacks.

Best regards,
Benjamin Vallon

**Comment by bastidererste** [comment]
they are all crashing in unity

**Comment by bastidererste** [comment]
did delete the folder contents.

it downloads the models.

but then:

C:\Program Files (x86)\ZED SDK\samples\bin>ZED_Body_Tracking_Viewer.exe

[ZED][Object Detection] AI model not found, downloading  \Done
 Done
[ZED][Object Detection] Please wait while the AI model is being optimized for your graphics card
 This operation will be run only once and may take a few minutes   Done[ZED] [Object Detection] MODEL_NOT_FOUND
[Sample][Error] enable Object Detection  | CORRUPTED SDK INSTALLATION : Corrupted SDK detected. Please reinstall the ZED SDK.
Exit program.

**Comment by Bvallon-sl** [comment]
Hi, 

We had some server issue yesterday, so the model you downloaded might be corrupted.
I joined the Multi_Class_Box_Fast model to this message.
Can you clean the ressources folder again, add the model I joined, and try to run a sample with the Multi_Class_Box_Fast model ?

Best regards,
Benjamin Vallon

[objects_performance_2.1.zip](https://github.com/stereolabs/zed-unity/files/6457769/objects_performance_2.1.zip)

**Comment by bastidererste** [comment]
cant find Multi_Class_Box_Fast :-/
there is a Multi_Class_Box though

and unity still crashes

**Comment by bastidererste** [comment]
when i copy the model to resources, set the model to Multi_Class_Box ZED_Object_detection_birds_eye_viewer goes some lines further, but still crashes

`101      ObjectDetectionRuntimeParameters detection_parameters_rt(detection_confidence);
`

**Comment by bastidererste** [comment]
> unity plugin : >>>>https://github.com/stereolabs/zed-unity/releases

thats's what i use

> Unity 2021.1.6f1
that's what im trying right now..

**Comment by bastidererste** [comment]
nope... didnt work

object detection doesnt work in unity and the ZED_SDK Examples.

I can run any other example but body tracking and object tracking...

**Comment by bastidererste** [comment]
the cpp example of object_detection_birds_view doesnt run

the python example of object_detection_birds_view runs without any issue 

thats weird

**Comment by Bvallon-sl** [comment]
Hi,

Sorry for the delay,

Can you verify both cpp and python sample you are running are using the same detection model ?
If not,  can you tell which detection models are working ? It would be nice to test it using a cpp sample.

Thanks for your help.

Best regards,
Benjamin Vallon

**Comment by bastidererste** [comment]
both versions of object_detection_birds_eye_view (cpp, py) use DETECTION_MODEL.MULTI_CLASS_BOX

cpp crashes
py runs
