### ISSUE TITLE
Problem with AR object slip phenomenon.

### ISSUE THREAD

**Issue by hagsac** [stereolabs/zed-unity#181]
Thank you always for your kind reply.
Referring to the ZED2 tutorial, create a simple object.
There is a problem when the camera is moved.

![image](https://user-images.githubusercontent.com/75370807/118135251-c2d9f200-b43d-11eb-9890-c23d235018a4.png)

A slight slip occurs about the motion of the object on the camera.
This slip phenomenon is a phenomenon that moves along the vertical or horizontal direction of the camera.

**However, after turning off Visual-inertial Tracking in Advanced Setting in Camera_ring, it operated normally without any slip phenomenon of the object.**
No documents were found for that advanced setting.
If the above setting is enabled, please tell me how it affects the execution of the tutorial above.

![image](https://user-images.githubusercontent.com/75370807/118135437-fd438f00-b43d-11eb-960a-0ed99bfb678b.png)

Problem occurred:  [Visual-inertial Tracking] = Active(cameraing default)
https://user-images.githubusercontent.com/75370807/118136653-4f38e480-b43f-11eb-8bcc-8b9ea33b79e4.mp4

Normal Operation: Inactive
https://user-images.githubusercontent.com/75370807/118139219-1cdcb680-b442-11eb-8a2c-61696da56c55.mp4

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for reaching us out.

This **Visual-inertial Tracking** parameter is the equivalent of the **PositionalTrackingParameters::enable_imu_fusion** parameter of the ZED SDK Api.

Your IMU calibration might be incorrect which can explain the really bad result you are getting when enabling it.

You can try to use the ZED Calibration tool (available in the ZED SDK/tools/) to reset the IMU and see if it solves your issue.

Best regards,
Benjamin Vallon

**Comment by hagsac** [comment]
I've found many ways, but I have the following problems.
I feel uncomfortable to implement the part about the calibration due to the following matters.

![image](https://user-images.githubusercontent.com/75370807/118491031-8f5ad880-b759-11eb-9d5f-17851afe4412.png)
Because my PC monitor is curved monitor. Is ZED calibration influenced by curved monitors?
Also, is IMU calibrated when using the camera calibration tool?
First of all, I want to change it to a perfect default, but Tool doesn't seem to have that function.

So I tried the following methods.
ZED Explorer attempted to update IMU or Camera Firmware.
![image](https://user-images.githubusercontent.com/75370807/118491849-5e2ed800-b75a-11eb-8056-36ba911a363b.png)

However, it was not updated normally.
![image](https://user-images.githubusercontent.com/75370807/118491976-7e5e9700-b75a-11eb-87d1-d033a7cd9c14.png)

After a long time on "2/7,"
![image](https://user-images.githubusercontent.com/75370807/118492327-df866a80-b75a-11eb-98f1-77891d5e3364.png)


In the event of an update failure, it is represented as '-1', which means that the ZED Driver must be released and reconnected from the window control panel to return to normal.

![image](https://user-images.githubusercontent.com/75370807/118492473-017fed00-b75b-11eb-8b22-f9cb2adcca19.png)

Camera update attempt is also a failure.
![image](https://user-images.githubusercontent.com/75370807/118493030-a1d61180-b75b-11eb-86cb-ce0deb0007aa.png)


![image](https://user-images.githubusercontent.com/75370807/118493176-c9c57500-b75b-11eb-8ec5-b5f4b843c6ac.png)

**Comment by Bvallon-sl** [comment]
Hi,

If you run the ZED Calibration tool with the **--cimu** argument in a console window, it will only run the IMU calibration part and skip the rest. You do not have to worry about it.

Best regards,
Benjamin Vallon

**Comment by hagsac** [comment]
Is this how everything works? I don't think anything has happened.
I'm sorry to bother you with so many questions.
![image](https://user-images.githubusercontent.com/75370807/118502218-786db380-b764-11eb-8d25-0c9763001063.png)

**Comment by Bvallon-sl** [comment]
Hi,

Are you using an old version of the ZED SDK ?
Can you try it with 3.5 ?

Best regards,
Benjamin Vallon

**Comment by hagsac** [comment]
We are using cuda 11.1 and SDK 3.5 cuda 11.1.
![image](https://user-images.githubusercontent.com/75370807/118521425-fdad9400-b775-11eb-8b47-184db4472c6d.png)

However, the results are as follows.
But all the examples are working fine.


And cuda 11.1 is installed normally.
I reinstalled SDK 3.4 cuda 11.1 version and checked it.
The image below is the evidence.
![image](https://user-images.githubusercontent.com/75370807/118521723-46654d00-b776-11eb-8f3f-ab873b38ed4f.png)

Of course, cmd IMU calibration is the same symptom in both versions 3.4 and 3.5.. ...............

Symptoms of the above cuda installation problem are SDK 3.5 cuda 11.1 and
SDJ3.5 cuda10...I understand that the same problem occurs in .
It seems to be a common problem in 3.5.
I checked in both places because I am using two PCs.

**Comment by hagsac** [comment]
Among the above questions, IMU or CAMERA's
Isn't there a problem with the firmware not being updated?

**Comment by hagsac** [comment]
cuda ver. check

![image](https://user-images.githubusercontent.com/75370807/118523273-f1c2d180-b777-11eb-8b4d-de2373149717.png)

**Comment by hagsac** [comment]
Good morning ~!
Please replay to my comments.

It seems that the existing AR problems
And SDK 3.5 problem  also need to be resolved.

I think the sdk 3.5 problem  is a problem  that all users have.

1.  Ar problem
2.  Sdk 3.5 problem
3.  Zed2 update problem

2021년 5월 18일 (화) 오전 12:26, BenjaminV_sl ***@***.***>님이 작성:

**Comment by P-yver** [comment]
Hi,
Indeed the IMU firmware can not be updated from Windows for the moment (only working under Linux) but your issue does not come from it (either 776 or 777).
We also faced the IMU drift and are currently working on a patch to fix it, I will let you know when it is online.

**Comment by hagsac** [comment]
Thank you for anshwer.

Your answer made me feel more at ease. :)

Please also answer the verification problem  when installing sdk 3.5.
After installing sdk 3.5, we did not find any major problems in the
examples except for AR problems, but it is not normal in the verification.
Are sdk 3.5 installation issues not having any impact when using zed2 ?

2021년 6월 3일 목요일, Pierre Yver ***@***.***>님이 작성:
