### ISSUE TITLE
ZEDManager always transforms `Camera_eyes`, even if tracking is disabled

### ISSUE THREAD

**Issue by crud89** [stereolabs/zed-unity#184]
I am building an application that uses external tracking only, so I want to prevent any transforms from ZED or the internal HMD tracking. When I add an ZED Stereo Rig to my scene and disable tracking and spatial memory, the `Camera_eyes` still get offset, resulting in my external tracking coordinates not matching with the actual camera position. Even setting *Tracking is static* to true, does not seem to affect the behavior.

![Transform Offset](https://user-images.githubusercontent.com/18394207/118949613-b3850800-b959-11eb-876c-d823db5fecb2.png)

The transform does stay constant, though. However, I was not able to find out where it is actually set. My current workaround is a component that forces the transform to be reset. This fixes the offset issue for me, however, I feel like this offsetting should not occur in the first place, if external tracking is used.

```csharp
public class ForceTransformReset : MonoBehaviour
{
    void Start()
    {
    }

    void Update()
    {
        this.transform.localPosition = new Vector3(0, 0, 0);
        this.transform.localRotation = Quaternion.identity;
    }
}
```

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for reaching us out.

If you disable the camera tracking, the plugin will still use the tracking on the headset to move the "Camera_Eyes" gameobject.
We do not have an option to completely remove the tracking, but you can do it by modifying some code.

In the ZedManager.cs, remove those 2 lines (https://github.com/stereolabs/zed-unity/blob/master/ZEDCamera/Assets/ZED/SDK/Helpers/Scripts/ZEDManager.cs#L2460) if the camera tracking is disabled,
or [these one](https://github.com/stereolabs/zed-unity/blob/master/ZEDCamera/Assets/ZED/SDK/Helpers/Scripts/ZEDManager.cs#L2438) if it is enabled.

Best regards,
Benjamin Vallon
