### ISSUE TITLE
The following error occurred in object detection.

### ISSUE THREAD

**Issue by hagsac** [stereolabs/zed-unity#190]
The following error occurred in object detection.
After setting up to detect only people in multi-class objects, a long time passed during testing and this phenomenon occurred.

![err](https://user-images.githubusercontent.com/75370807/121768999-2b7ed080-cb9c-11eb-8099-31759f073631.PNG)
![err2](https://user-images.githubusercontent.com/75370807/121769002-2caffd80-cb9c-11eb-8c91-376381ad2f80.PNG)

**Comment by Bvallon-sl** [comment]
Hi,

Can you try to set the SENSING MODE to **FILL** (see attachment) ? This way, the depth map will be complete and it won't return NaN values.

![depth_fill](https://user-images.githubusercontent.com/60651082/121860349-0b185880-ccf9-11eb-9dcf-429fa0b31cc0.PNG)


Best regards,
Benjamin Vallon

**Comment by hagsac** [comment]
I'm always using the same [FILL] mode.
I recently made an application using 3D Detector.
As a result of the build, we recorded more than 3 hours afterward.
After a long time, the cube was created well, but the Tag ID was not printed (sometimes printed). It seems to be the same problem as above.
The error log could not be checked because it was executed as an exe.

**Comment by hagsac** [comment]
Due to the size of the attached file, it is difficult to tell the details of the problem.
It is not possible with github mail.
Do you have any other email addresses?
hagsac@gmail.com

**Comment by Bvallon-sl** [comment]
Hi,

You can send a message at support@stereolabs.com.

Best,
Benjamin Vallon

**Comment by Bvallon-sl** [comment]
Hi again,

I'm not sure why this vector has Infinity value yet but I updated the code to avoid this error. You can pull the URP or Master branch.

Best regards,
Benjamin Vallon
