### ISSUE TITLE
Human skeleton recognition problem

### ISSUE THREAD

**Issue by yizes** [stereolabs/zed-unity#193]
I want to use zed2 to judge some movements, such as waving and jumping. However, there seems to be no relevant example tutorial in unity Integration Tutorial. I wonder if there is any way to help me solve this problem faster.

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for reaching us out.

For the moment, we do not have gesture recognition features integrated to our skeleton tracking module.
You will need to use external ressources or develop your own detector based on data output by our Body tracking module.

Best regards,
Benjamin Vallon

**Comment by nhruch** [comment]
Hey Benjamin,

Do you have any recommendations as to which external ressources we might be able to use for gesture recognition? Also, 
is gesture recognition on the development schedule?

Thanks for all your work and these examples. 

- Nick

**Comment by Bvallon-sl** [comment]
Hi,

We do not plan to integrate gesture recognition in the ZED SDK for the moment.

I do not have external ressource to recommend but I think you might want to look into AI-based systems.
The leap motion cameras provides some gesture recognition, maybe you can look into it as well.

Best regards,
Benjamin Vallon
