### ISSUE TITLE
Bounding box problem

### ISSUE THREAD

**Issue by hagsac** [stereolabs/zed-unity#194]
Hello. Thank you for your quick reply.
When a person is detected in a bird view, the bounding box is greatly enlarged.
I'm testing the floor at about 30? degrees, 7 to 8 meters high.
When a person moves to the bottom and edge of the camera view screen, the bounding box becomes significantly larger than the object size.  After setting the bounding box to Fixed, when tested, the results are judged normally in proportion to the sense of perspective. 
If this problem is not solved, 3D detection is meaningless.
It's a big problem with my project.

![20210622_155709](https://user-images.githubusercontent.com/75370807/122878283-8c639100-d372-11eb-9461-ae1a2f9a1b8a.jpg)
![20210622_155658](https://user-images.githubusercontent.com/75370807/122878289-8ec5eb00-d372-11eb-84a5-568b82ac97e7.jpg)

**Comment by Bvallon-sl** [comment]
Hi,

The thing is the width and the length of the bounding box are the same, meaning that the top/bottom face are always a square, which can explain why the bounding box is so large.

What specific informations do you need for your project ?
Even if the box is large, you can have the 3D position of the person.

Best regards,
Benjamin Vallon

**Comment by hagsac** [comment]
Good morning.
To help you understand, I will explain in comparison with unsetting the [transform scale] setting of the 3D Object Visualizer.
The [transform box scale] setting is a great feature.
So I want to use it.
However, due to the following large deviations, it is difficult to use.
In my opinion, this equates to losing the benefits of 3D sensing.

![image](https://user-images.githubusercontent.com/75370807/123422854-c1cde000-d5f9-11eb-82bd-15d669a5e2fa.png)

![image](https://user-images.githubusercontent.com/75370807/123422862-c5f9fd80-d5f9-11eb-869e-f53db9b29074.png)


I'm making a safety system.
However, it is not easy to set in consideration of the increase in the bound box size depending on the location of the danger zone setting.

![image](https://user-images.githubusercontent.com/75370807/123422879-cb574800-d5f9-11eb-99a2-c10ae84c4c98.png)

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for the detailed informations, I now have a better understanding of your situation.
I see two solutions : 
- Do not use the transform box scale, and only use boxes with fixed sized.
- Using the skeleton tracking model and create your own "minimal" bounding box with the joints position. 

 Best regards,
Benjamin Vallon

**Comment by hagsac** [comment]
hi! 

Thanks for the sincere reply.
I've reviewed your answer.

Your solution first:
![image](https://user-images.githubusercontent.com/75370807/131960811-f2324874-7c77-4835-a124-0104f6a21e54.png)

Your solution second:
Currently, the application I am making is processed in the SBC (Edge PC) unit.If you use a skeleton, it has been confirmed that it is very difficult to operate with low specifications.Shouldn't this be a problem that should be considered from the correction of camera angle and depth?

have a good day. 
chang in ho.
