### ISSUE TITLE
Difference between mono and stereo prefabs 

### ISSUE THREAD

**Issue by sararom15** [stereolabs/zed-unity#198]
Hello, 
I'm trying to retrieve **depth information** from the camera. I'm using **mono camera prefabs** in Unity and I recognized that it is giving as output the value of the depth as well. 
I thought it was only possible with the stereo camera, so I want to ask you **why and how the depth information is available with the mono camera** too. 

I'm waiting for your response. 
Thank you in advance.

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for reaching us out.

Indeed, the mono camera prefab only displays one camera image. However, the depth map is still internally computed using both left and right sensors. 

Best regards,
Benjamin Vallon
