### ISSUE TITLE
Is it possible to implement like the floor normal of the Sretero Lab video?

### ISSUE THREAD

**Issue by hagsac** [stereolabs/zed-unity#206]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

<img width="1111" alt="capture" src="https://user-images.githubusercontent.com/75370807/134627448-fda22402-e2a5-45aa-a274-b58558f77103.png">

1. Is it possible to implement normals as follows?
There are too many differences from the basic example.
Are there other programming languages ​​with that implementation available?

2. The floor detection in the example is too different from the normal implementation on Stereolab's homepage. can't be beautiful.

### Use-Case

Can you provide a beautiful detection example like the video in Stereolab above?

Have a nice day!

**Comment by Bvallon-sl** [comment]
Hi,

The floor plane position can be retrieved with the ZEDCamera.findFloorPlane() function. Once you have the floor plane equation, you can place a grid (as a 3d object  for example) at this location.

Unfortunately, the code used to generate this video is not available.

Best regards,
Benjamin Vallon
