### ISSUE TITLE
Object Detection 2D masks have glitches when more than one human detected

### ISSUE THREAD

**Issue by brontesprocessing** [stereolabs/zed-unity#208]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Object Detection 2D masks have glitches when more than one human detected

### Steps to Reproduce

1. Create a new project and import ZED_Unity_Plugin_v3.5.2.unitypackage
2. Open scene Assets\ZED\Examples\Object Detection\Scenes\2D Object Detection
3. Select ZED_Rig_Mono and check Enable 2D MASK in the inspector 
4. Then change Object Detection Model to HUMAN_BODY_ACCURATE
5. Select2D Object Visualizer and check-in inspector Show Object Mask

### Expected Result

Masks for all detected bodies shall be provided.

### Actual Result

It looks like at least one mask is always broken (having glitches)
![image](https://user-images.githubusercontent.com/70581143/135606223-35830807-f655-4376-8586-c8dafe6e36db.png)

### ZED Camera model

ZED2i

### Environment

```shell
Windows 10
Intel i7 (9th gen)
ZED SDK: 3.5.2
NVidia RTX 2070
```

**Comment by Bvallon-sl** [comment]
Hi,

Sorry for the delay. This issue will be fixed in the next patch (3.6.3) which will be available next week.

Best,
Benjamin V.
