### ISSUE TITLE
Unity crashes on Zed 2i self calibration 

### ISSUE THREAD

**Issue by nhruch** [stereolabs/zed-unity#210]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hey folks,

We have a unity project that in some conditions crashes during self calibration. There are two Zed 2i cameras; one in the front and one in the back. On the start of the application we are able to see the front facing image pointed into the room. Shortly after that image appears, Unity crashes with the following stack trace:

`
Project by Company [version: Unity 2020.3.17f1_a4537701e4ab]

sl_zed64.dll caused an Access Violation (0xc0000005)
  in module sl_zed64.dll at 0033:4834fe3d.

Error occurred at 2021-10-06_132930.
C:\conference\install\unity\project.exe, run by Conference

9% physical memory in use.
65388 MB physical memory [59343 MB free].
3903 MB process peak paging file [3839 MB used].
1436 MB process peak working set [1408 MB used].
System Commit Total/Limit/Peak: 10156MB/75116MB/12898MB
System Physical Total/Available: 65388MB/59343MB
System Process Count: 165
System Thread Count: 2469
System Handle Count: 64566
Disk space data for 'C:\Users\conference\AppData\Local\Temp\Company\project\Crashes\Crash_2021-10-06_092917794\': 360443211776 bytes free of 998865104896 total.

Read from location 0000000000000000 caused an access violation.

Context:
RDI:    0x0000000000000000  RSI: 0x000000f8dd2ca948  RAX:   0x000000f8dd2caa50
RBX:    0x0000000000000000  RCX: 0x000000f8dd2caa50  RDX:   0x0000000000000000
RIP:    0x00007ff84834fe3d  RBP: 0x000000f8dd2ca890  SegCs: 0x0000000000000033
EFlags: 0x0000000000010246  RSP: 0x000000f8dd2ca788  SegSs: 0x000000000000002b
R8:     0x0000000000000001  R9:  0x0000000000000000  R10:   0x0000000000000000
R11:    0x0000000000000000  R12: 0x0000000000000000  R13:   0x000000f8dd2ca7f8
R14:    0x000000f8dd2cabe0  R15: 0x000000f8dd2cac78

Bytes at CS:EIP:
f3 41 0f 10 01 49 3b d0 7e 64 48 83 fa 04 7e 40 

Mono DLL loaded successfully at 'C:\conference\install\unity\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll'.

Stack Trace of Crashed Thread 2568:
0x00007FF84834FE3D (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF8483544F3 (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF8483665CE (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF8483662B0 (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF848365A66 (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF8483671FB (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF84836B2AC (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF8483351DA (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF848D380A7 (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF848CEC3F1 (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF848D49078 (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF848CF2CCE (sl_zed64) VfF7SSpxHq::getScoreQ
0x00007FF88B37418C (sl_unitywrapper) dllz_update_self_calibration
0x000002304DEDD74D (Assembly-CSharp) sl.ZEDCamera.dllz_grab()
0x000002304DEDD5DB (Assembly-CSharp) sl.ZEDCamera.Grab()
0x000002304DEDD243 (Assembly-CSharp) ZEDManager.AcquireImages()
0x000002304DEDCA03 (Assembly-CSharp) ZEDManager.ThreadedZEDGrab()
0x000002327FF9F9C6 (mscorlib) System.Threading.ThreadHelper.ThreadStart_Context()
0x000002327FF9F41E (mscorlib) System.Threading.ExecutionContext.RunInternal()
0x000002327FFBFD9B (mscorlib) System.Threading.ExecutionContext.Run()
0x000002327FFBFBAB (mscorlib) System.Threading.ExecutionContext.Run()
0x000002327FFBF9B3 (mscorlib) System.Threading.ThreadHelper.ThreadStart()
0x00000231E38C3664 (mscorlib) System.Object.runtime_invoke_void__this__()
0x00007FF84C86E660 (mono-2.0-bdwgc) mono_get_runtime_build_info
0x00007FF84C7F2AE2 (mono-2.0-bdwgc) mono_perfcounters_init
0x00007FF84C7FBD12 (mono-2.0-bdwgc) mono_runtime_invoke_array
0x00007FF84C816C2F (mono-2.0-bdwgc) mono_unity_managed_callstack
0x00007FF84C816976 (mono-2.0-bdwgc) mono_unity_managed_callstack
0x00007FF8A2137034 (KERNEL32) BaseThreadInitThunk
0x00007FF8A2D7CEC1 (ntdll) RtlUserThreadStart
`

Currently, the display is about a foot from the wall so while the front camera has plenty of space to work with, the back camera does not. These crashes began occurring after the display was moved from one location (not sure how close it was to the wall then) to a location that is definitely up against a wall.

I believe I ran into this type of crash before when I covered the cameras sensor with a sheet of paper. Almost as if the camera creates a bad calibration number and then falls apart on that. When I removed the piece of paper it started working again. This was not always consistent though.  

### Steps to Reproduce

1. Initialize Zed 2i while covered
2.
3.
...

### Expected Result

We are able to call Grab() without crashing.

### Actual Result

Unity crashes and creates a stack trace. 

### ZED Camera model

ZED2i

### Environment

```shell
Windows 10
AMD Ryzen Threadripper PRO 3955WX
64GB Memory
RTX 4000
CUDA 11.0
Zed SDK 3.5.3
```

**Comment by Bvallon-sl** [comment]
Hi,

I was not able to reproduce the issue.
Could you send me a small project with an example scene that reproduces the crash (we may be using different settings).
Or at least, the settings you used in the ZEDManager script.

I don't know if you can, but the best would be to share a SVO that causes the crash.

Also, did you try to use your other camera ? 

You can send me that here or directly at support@stereolabs.com if you prefer.

Best regards,
Benjamin Vallon
