### ISSUE TITLE
Is it possible to use GreenScreen on a Stereo Rig ? [ Unity ]

### ISSUE THREAD

**Issue by Gnoknop** [stereolabs/zed-unity#222]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Hello there,

I'd like to use the GreenScreen Component with the HMD HTC Vive ( Both Eyes ), using unity.

Here is an example ( not mine, but 100 % what i'm trying to achieve ) : 

https://www.youtube.com/watch?v=w7jpwirvFlA

Is it possible ?

Thank you for your help

**Comment by Bvallon-sl** [comment]
Hi,

Please take a look at our [Green screen VR](https://www.stereolabs.com/docs/unity/green-screen-vr/) documentation which explains how to use our Zed-mini camera to create AR apps with a green screen.

If you have additional questions, do not hesitate to write us directly at support@stereolabs.com 

Best regards,
Benjamin Vallon
