### ISSUE TITLE
No downloadable version for Unity plugin 3.6.4.

### ISSUE THREAD

**Issue by lvgeng** [stereolabs/zed-unity#224]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Currently, there is not a easy to use version for Unity Plugin 3.6.4 (https://github.com/stereolabs/zed-unity/releases)

If it is possible, would you mind giving some instruction on how to use the source code?

**Comment by Bvallon-sl** [comment]
Hi,

To upgrade your current project with the new unity plugin :
Once you downloaded the zed unity plugin, you just need to replace your current ZED folder by the one available in zed-unity3.6.4/ZEDCamera/Asset. 

I'll add the unity package if you prefer you can use that.

Best,
Benjamin Vallon
