### ISSUE TITLE
plugin v3.7 skeletonscene crash

### ISSUE THREAD

**Issue by gksthf2845** [stereolabs/zed-unity#229]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

![crash](https://user-images.githubusercontent.com/20723721/155959913-d00ca818-c5d8-4d43-94a0-658ee9be4c88.PNG)

other scene  doesn't crash and works well.

confirm ZED Diagnostic.exe
![sdk](https://user-images.githubusercontent.com/20723721/155961535-8d664d87-2e59-4d5f-b780-7ad20849ad13.PNG)

but, explorer did works wel
![캡처6](https://user-images.githubusercontent.com/20723721/155961816-7b6ff83c-278a-44f0-9cc8-274f0f5f56ee.PNG)
l

### Steps to Reproduce

1. installed cuda 11.5 ,  zed SDK 3.7  
2.run unity project in github zedplugin 3.7 version
3.play example scene at skeleton

(removed old sdk)

### Expected Result

nothing.

just unity proccese crashed.

### Actual Result

unity proccese crashed.

### ZED Camera model

ZED2

### Environment

```shell
window,
geforce 1060
graphic driver latest version.

testted unity version
 2021.1.20f1
 2020.3.18f
 2020.3.15f
 2020.1.10f
```

**Comment by Bvallon-sl** [comment]
Hi,

Could you send the diagnostic report at support@stereolabs.com ? 

If possible, the crash report from Unity would be very useful as well. You can find it in :

`C:\Users\USERNAME\AppData\Local\Temp\Unity\Editor\Crashes
`

Note that I pushed a fix this morning on the master branch (some merge conflicts unresolved). you can pull and try again.

Best regards,
Benjamin Vallon

**Comment by gksthf2845** [comment]
> t [support@stereolabs.com](mailto:support@stereolabs.com)

can't save diagnostic report. 
After checking the graphic card, immediately process downed.

unity crash report here.

[error.log](https://github.com/stereolabs/zed-unity/files/8166194/error.log)

translation.
잘못된 주소를 액세스하려고 했습니다 >> tried to access the wrong address.

**Comment by Bvallon-sl** [comment]
Is the OD model already optimized on your computer ?

If you don't know or is not optimized, can you try to run the body tracking cpp sample (available in the ZED SDK folder, in sample/) ?

Once the model is optimized, comment these lines in the wrapper and try again :

https://github.com/stereolabs/zed-unity/blob/master/ZEDCamera/Assets/ZED/SDK/Helpers/Scripts/ZEDManager.cs#L2688 
to 

https://github.com/stereolabs/zed-unity/blob/master/ZEDCamera/Assets/ZED/SDK/Helpers/Scripts/ZEDManager.cs#L2693

Best regards,
Benjamin Vallon

**Comment by gksthf2845** [comment]
sorry , i can't understand mean of OD model .
I don't know what it means even if I search it on Google.
how can i main.cpp build and run?

 i  wrapped what you said and there was no crash.
 but not show ybot model

**Comment by Bvallon-sl** [comment]
Sorry I meant [Object Detection Model](https://www.stereolabs.com/docs/api/group__Object__group.html#ga4a212b90726adaaf0fae801b1cc913f4). It's part of our SDK API. When you run the Object detection module, you choose a OD model which allows you to detect different objects in the scene. For example, the **HUMAN_BODY_X" model detects the human skeletons whereas the **MULTI_CLASS_BOX* model detects the several classes of objects and returns their bounding box.

To build and run a cpp program, you have to follow theses steps (link to the documentation [here](https://www.stereolabs.com/docs/app-development/cpp/windows/).
You can try to run a sample and see if it works but we should focus on the error you are getting in the Diagnostic tool as it seems the SDK is not correctly installed. 
Do you have any error message when running the Diagnostic tool during the ZED SDK part (which is red in your image) ?

**Comment by gksthf2845** [comment]
thank you, Today Install ZED SDK one more.

done SDK!  diagnostic tool collectly work.

please see this diagnostic log.

{
    "AI Models": {
        "info": [
            "MULTI CLASS DETECTION is not optimized",
            "MULTI CLASS MEDIUM DETECTION is not optimized",
            "MULTI CLASS ACCURATE DETECTION is not optimized",
            "HUMAN BODY FAST DETECTION is not optimized",
            "HUMAN BODY MEDIUM DETECTION is not optimized",
            "PERSON HEAD DETECTION is not optimized",
            "REID ASSOCIATION is not optimized",
            "NEURAL DEPTH is not optimized"
        ],
        "valid": [
            "HUMAN BODY ACCURATE DETECTION is optimized"
        ]
    },
    "Camera Test": {
        "InternalDevicesCount": 2,
        "ZEDCount": 1,
        "camera": {
            "Device ID": 1,
            "Firmware": 1523,
            "Init Output": "OK",
            "Model": "ZED 2",
            "Serial Number": 25329672,
            "valid": [
                "<b>Camera: </b>ZED 2",
                "<b>Firmware: </b>1523"
            ]
        },
        "resolutions": {
            "HD1080@15": {
                "fps (input)": 15,
                "fps (output)": 15,
                "height (input)": 1080,
                "height (output)": 1080,
                "initialization": "OK",
                "status": true,
                "width (input)": 1920,
                "width (output)": 1920
            },
            "HD1080@30": {
                "fps (input)": 30,
                "fps (output)": 30,
                "height (input)": 1080,
                "height (output)": 1080,
                "initialization": "OK",
                "status": true,
                "width (input)": 1920,
                "width (output)": 1920
            },
            "HD2K@15": {
                "fps (input)": 15,
                "fps (output)": 15,
                "height (input)": 1242,
                "height (output)": 1242,
                "initialization": "OK",
                "status": true,
                "width (input)": 2208,
                "width (output)": 2208
            },
            "HD720@15": {
                "fps (input)": 15,
                "fps (output)": 15,
                "height (input)": 720,
                "height (output)": 720,
                "initialization": "OK",
                "status": true,
                "width (input)": 1280,
                "width (output)": 1280
            },
            "HD720@30": {
                "fps (input)": 30,
                "fps (output)": 30,
                "height (input)": 720,
                "height (output)": 720,
                "initialization": "OK",
                "status": true,
                "width (input)": 1280,
                "width (output)": 1280
            },
            "HD720@60": {
                "dropCount": 0,
                "fps (input)": 60,
                "fps (output)": 49,
                "height (input)": 720,
                "height (output)": 720,
                "imageCount": 500,
                "initialization": "OK",
                "status": true,
                "tearingCount": 0,
                "width (input)": 1280,
                "width (output)": 1280
            },
            "VGA@100": {
                "fps (input)": 100,
                "fps (output)": 59,
                "height (input)": 376,
                "height (output)": 376,
                "initialization": "OK",
                "status": true,
                "width (input)": 672,
                "width (output)": 672
            },
            "VGA@15": {
                "fps (input)": 15,
                "fps (output)": 15,
                "height (input)": 376,
                "height (output)": 376,
                "initialization": "OK",
                "status": true,
                "width (input)": 672,
                "width (output)": 672
            },
            "VGA@30": {
                "fps (input)": 30,
                "fps (output)": 30,
                "height (input)": 376,
                "height (output)": 376,
                "initialization": "OK",
                "status": true,
                "width (input)": 672,
                "width (output)": 672
            },
            "VGA@60": {
                "fps (input)": 60,
                "fps (output)": 43,
                "height (input)": 376,
                "height (output)": 376,
                "initialization": "OK",
                "status": true,
                "width (input)": 672,
                "width (output)": 672
            }
        },
        "sensors": {
            "Firmware": 776,
            "Init Output": "OK",
            "Model": "ZED 2 (MCU)",
            "Serial Number": 25329672
        }
    },
    "Graphics Card": {
        "deviceCount": 1,
        "deviceDriverVersion": 11060,
        "devices": [
            {
                "arch": "Pascal",
                "computeCapability": "6.1",
                "cores": 1280,
                "name": "NVIDIA GeForce GTX 1060 6GB",
                "totalMemoryBytes": "6442123264",
                "totalMemoryMB": 6143.6875
            }
        ],
        "initResult": 0,
        "valid": [
            "<b>Graphics card: </b> NVIDIA GeForce GTX 1060 6GB"
        ]
    },
    "Processor": {
        "OS": "Windows 10 FallCreators",
        "avxSupported": true,
        "coreCount": "6",
        "cpu": "AMD Ryzen 5 1600 Six-Core Processor            ",
        "datetime": "2022-03-07 11:19:40",
        "hyperThreading": "1",
        "motherboard": "X370 GAMING PRO CARBON (MS-7A32), Micro-Star International Co., Ltd",
        "ramCapacity": "31.9481",
        "ramUsage": "0",
        "ramUsed": "14.6032",
        "threadCount": "12",
        "valid": [
            "<b>Processor: </b> AMD Ryzen 5 1600 Six-Core Processor            ",
            "<b>Motherboard: </b> X370 GAMING PRO CARBON (MS-7A32), Micro-Star International Co., Ltd"
        ]
    },
    "USB": {
        "ASMediaFound": false,
        "CorruptedFirmware": false,
        "MCUDetected": true,
        "OC_Cam_Detected": false,
        "OtherUSBDevices": [
        ],
        "USBList": [
            {
                "USBMode": 3,
                "USB_path": "/3",
                "bDescriptorType": 1,
                "bDeviceProtocol": 1,
                "bLength": 18,
                "bMaxPacketSize0": 9,
                "bNumConfigurations": 1,
                "bcdDevice": "1.0",
                "bcdUSB": "3.0",
                "bcdUSBClass": 239,
                "bcdUSBSubClass": 2,
                "busNumber": 1,
                "device": "ZED2",
                "iManufacturer": 1,
                "iProduct": 2,
                "iSerial": 0,
                "idProduct": "0xf780",
                "idVendor": "0x2b03"
            },
            {
                "USB_path": "/17",
                "idProduct": "0x2113",
                "idVendor": "0x413c"
            },
            {
                "USB_path": "/2",
                "idProduct": "0x030e",
                "idVendor": "0x0bb4"
            },
            {
                "USB_path": "/18",
                "idProduct": "0xa09f",
                "idVendor": "0x04d9"
            },
            {
                "USB_path": "/11",
                "idProduct": "0x2512",
                "idVendor": "0x0424"
            },
            {
                "USB_path": "/22",
                "idProduct": "0x0001",
                "idVendor": "0x0a12"
            },
            {
                "USBMode": 2,
                "USB_path": "/11/2",
                "bDescriptorType": 1,
                "bDeviceProtocol": 0,
                "bLength": 18,
                "bMaxPacketSize0": 64,
                "bNumConfigurations": 1,
                "bcdDevice": "3.8",
                "bcdUSB": "2.0",
                "bcdUSBClass": 0,
                "bcdUSBSubClass": 0,
                "busNumber": 1,
                "device": "ZED2 MCU",
                "iManufacturer": 1,
                "iProduct": 2,
                "iSerial": 3,
                "idProduct": "0xf781",
                "idVendor": "0x2b03"
            },
            {
                "USB_path": "/18",
                "idProduct": "0xa09f",
                "idVendor": "0x04d9"
            }
        ],
        "USBMode": 3,
        "ZED Camera Module Detected": 63360,
        "ZED MCU Module Detected": 63361,
        "ZEDDetected": true,
        "captureDevices": [
            {
                "CompatibleIDs": "UMB\\http://schemas.microsoft.com/windows/2006/08/wdp/scan/ScannerServiceType",
                "Description": "WSD �� �X",
                "DeviceName": "SEC84251935893B",
                "Driver": "{6bdd1fc6-810f-11d0-bec7-08002be2092f}\\0000",
                "Location": "http://192.168.50.225:8018/wsd",
                "Manufacturer": "Samsung Electronics Co., Ltd.",
                "Name": "SWD",
                "PhysicalName": "\\Device\\000000c9"
            }
        ],
        "controllers": [
            {
                "CompatibleIDs": "USB\\USB30_HUB",
                "Description": "|\u0018 SuperSpeed USB �\f",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0046",
                "Location": "Port_#0004.Hub_#0004",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": ""
            },
            {
                "CompatibleIDs": "USB\\USB20_HUB",
                "Description": "|\u0018 USB �\f",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0057",
                "Location": "Port_#0001.Hub_#0012",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": ""
            },
            {
                "CompatibleIDs": "",
                "Description": "USB �� �\f(USB 3.0)",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0003",
                "Location": "",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": "\\Device\\USBPDO-1"
            },
            {
                "CompatibleIDs": "USB\\USB20_HUB",
                "Description": "|\u0018 USB �\f",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0019",
                "Location": "Port_#0001.Hub_#0002",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": ""
            },
            {
                "CompatibleIDs": "",
                "Description": "USB �� �\f(USB 3.0)",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0004",
                "Location": "",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": "\\Device\\USBPDO-0"
            },
            {
                "CompatibleIDs": "USB\\USB20_HUB",
                "Description": "|\u0018 USB �\f",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0049",
                "Location": "Port_#0004.Hub_#0008",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": ""
            },
            {
                "CompatibleIDs": "USB\\USB20_HUB",
                "Description": "|\u0018 USB �\f",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0044",
                "Location": "Port_#0001.Hub_#0002",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": ""
            },
            {
                "CompatibleIDs": "USB\\USB30_HUB",
                "Description": "|\u0018 SuperSpeed USB �\f",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0043",
                "Location": "Port_#0005.Hub_#0002",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": ""
            },
            {
                "CompatibleIDs": "USB\\USB20_HUB",
                "Description": "|\u0018 USB �\f",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0021",
                "Location": "Port_#0001.Hub_#0003",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": ""
            },
            {
                "CompatibleIDs": "USB\\USB20_HUB",
                "Description": "|\u0018 USB �\f",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0018",
                "Location": "Port_#0004.Hub_#0002",
                "Manufacturer": "(\\",
                "Name": "USB",
                "PhysicalName": ""
            },
            {
                "CompatibleIDs": "PCI\\VEN_1022&DEV_43B9&REV_02",
                "Description": "USB xHCI ܩ 8�� ��d�",
                "DeviceName": "AMD USB 3.1 U� ",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0000",
                "Location": "PCI �� 3, �X 0, 0� 0",
                "Manufacturer": "|\u0018 USB xHCI 8�� ��d�",
                "Name": "PCI",
                "PhysicalName": "\\Device\\NTPNP_PCI0021"
            },
            {
                "CompatibleIDs": "PCI\\VEN_1022&DEV_145C&REV_00",
                "Description": "USB xHCI ܩ 8�� ��d�",
                "DeviceName": "AMD USB 3.0 U� ",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0001",
                "Location": "PCI �� 37, �X 0, 0� 3",
                "Manufacturer": "|\u0018 USB xHCI 8�� ��d�",
                "Name": "PCI",
                "PhysicalName": "\\Device\\NTPNP_PCI0028"
            }
        ],
        "valid": [
            "<b>USB Bandwidth: </b> OK"
        ]
    },
    "ZED SDK": {
        "CUDA Toolkit version": "V11.5.50 -->located in C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5/bin/nvcc.exe",
        "CUDA loading": false,
        "CUDA_reachable": true,
        "ZED SDK Version (Diag)": "3.7.0",
        "ZED SDK Version (RT)": "3.7.0",
        "ai": {
            "checkAI": true,
            "cudaVersion": 11050,
            "cudnnCudartVersion": 11030,
            "cudnnVersion": 8201,
            "cudnnVersionExpected": 8201,
            "tensorVersion": 8201
        },
        "binFiles": [
            "cudnn64_8.dll",
            "cudnn_adv_infer64_8.dll",
            "cudnn_adv_train64_8.dll",
            "cudnn_cnn_infer64_8.dll",
            "cudnn_cnn_train64_8.dll",
            "cudnn_ops_infer64_8.dll",
            "cudnn_ops_train64_8.dll",
            "nvinfer.dll",
            "nvinfer_builder_resource.dll",
            "nvinfer_plugin.dll",
            "nvonnxparser.dll",
            "nvparsers.dll",
            "sl_ai64.dll",
            "sl_zed64.dll"
        ],
        "driverVersion": "511.79",
        "drivervDllVersion": "30.0.15.1179",
        "resourcesFiles": [
            "skeleton_accurate_2.0.model",
            "skeleton_accurate_2.0.model_optimized-aaaaw-1-61-11050-8201-8201"
        ],
        "resourcesFilesExpected": [
            "objects_performance_2.1"
        ],
        "runtimeDllVersion": 11050,
        "valid": [
            "<b>ZED SDK version:</b> 3.7.0",
            "<b>CUDA version:</b> V11.5.50"
        ]
    }
}

**Comment by Bvallon-sl** [comment]
Hi,

It looks like an usb issue. Can you make sure the camera is connected using a USB 3.0  port ?

**Comment by gksthf2845** [comment]
> yes , thanks. 

i know camera doesn't work unless it's usb 3.0.

**Comment by lmbarns** [comment]
I have a similar issue, the other examples work in Unity but the skeleton demo hangs and then crashes Unity but without an error prompt and no crash log generated. 

Unity 2020.3.13f1 LTS
ZED_SDK_Windows10_cuda11.7_v3.7.6.exe sdk version
ZED_Unity_Plugin_v3.7.1.unitypackage 

The other examples work, and without a crash log it's hard to figure out what's wrong.

**Comment by jugal-kanousei** [comment]
Hi there,
did you manage to figure out? I'm having the same issue, Unity Editor just hangs and crashes on play.

Unity 2021.3.4f1 LTS
ZED_SDK_Windows11_cuda11.7 
ZED_Unity_Plugin_v3.8.unitypackage

**Comment by Bvallon-sl** [comment]
Hi,

 The AI models need to be downloaded and optimized before the first use.
This process takes a few minutes and is freezing the Unity Editor window until it finishes (this will be fixed in the near future).

Until then, I suggest you to doing this process outside of Unity.
Here is the documentation explaining you how to do it; https://support.stereolabs.com/hc/en-us/articles/9747407795223-How-can-I-optimize-the-ZED-SDK-AI-models-manually-.

Best regards
