### ISSUE TITLE
[OpenXR] Doesn't work without SteamVR in Unity 2021/20lts

### ISSUE THREAD

**Issue by Xovval** [stereolabs/zed-unity#233]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When configured as seen below, the HMD (Vive Pro) doesn't recieve any video data but inside the editor, the expected result is seen. After a bit of debugging, it seems that the variables "isStereoRig" and "stereoTargetEye "aren't set correctly (false and StereoTargetEyeMask.None) because "hasXRDevice()" doesn't return true in the first few frames. 
Resolving this issue (by starting the xrDisplaySubsystem inside "hasXRDevice()", if not already running) and manually enabling the cameras of the game objects Left_eye and Right_eye during runtime leads to the expected output on the right eye but to a wrong display on the left eye (either the virtual objects missing or the see-through-plane being visible (blue) and not the captured video.

### Steps to Reproduce

1. Downloading Unity 2021.2.12f
2. CUDA init
3. ZED init
4. Create a new 3D project
5. Edit -> Project Settings -> XR Plugin Management -> Install + Set Vive Input Actions
6. (If necessary: Edit -> Project Settings -> Player -> Other Settigns -> Active Input Handlings: Both
7. Add the ZED Plugin
8. Open a example scene (e.g. Planetarium)
9. Hit play

### Expected Result

Visible output of  the HMD as seen inside the Unity editor.

### Actual Result

No output inside the HMD - the screen keeps blank. (Not the Vive init surrounding)

### ZED Camera model

ZED Mini

### Environment

```shell
OS: Windows 10 - 21H1
CPU: Intel i9-11900K
GPU: NVIDIA RTX 3090
CUDA: 11.5
ZED SDK version: 3.7
```

### Anything else?

There are no issues with ZED Diagnostics and sensor output of the other zed utilities seems correct as well.

**Comment by Bvallon-sl** [comment]
Hi,

You need to download the OpenVR package to make the ZED Unity plugin work with SteamVR headset. It available here : https://github.com/ValveSoftware/steamvr_unity_plugin

Best,
Benjamin Vallon

**Comment by Xovval** [comment]
Hi,

thank you for your fast reply!
Regarding your answer, I might assume that it is not possible to bypass this requirement?
Sadly and because of some compability issues with another headset, it's not possible for me/us to use SteamVR.

Best,
Sadeiko

**Comment by Bvallon-sl** [comment]
Hi,

Sorry I did see your message. Your request has been added to our backlog, you can close this issue.

Best,
Benjamin Vallon

**Comment by Xovval** [comment]
Alright!
