### ISSUE TITLE
The Model * MULTI_CLASS_BOX_ACCURATE * has not been downloaded/optimized. Use the ZED Diagnostic tool to download/optimze all the AI model you plan to use.

### ISSUE THREAD

**Issue by AsIfPu** [stereolabs/zed-unity#234]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I can't run the Object Detection and the SkeletonTracking. Other Examples are normal.I think it's the problem of ai models.

The Model * MULTI_CLASS_BOX_ACCURATE * has not been downloaded/optimized. Use the ZED Diagnostic tool to download/optimze all the AI model you plan to use.
UnityEngine.Debug:LogError (object)
ZEDManager:StartObjectDetection () (at Assets/ZED/SDK/Helpers/Scripts/ZEDManager.cs:2691)
ZED3DObjectVisualizer:OnZEDReady () (at Assets/ZED/Examples/Object Detection/Scripts/ZED3DObjectVisualizer.cs:161)
ZEDManager/<InitZED>d__295:MoveNext () (at Assets/ZED/SDK/Helpers/Scripts/ZEDManager.cs:1974)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

Object Detection failed to start. (Error: MODULE_NOT_COMPATIBLE_WITH_CAMERA )
UnityEngine.Debug:Log (object)
ZEDManager/<startObjectDetection>d__319:MoveNext () (at Assets/ZED/SDK/Helpers/Scripts/ZEDManager.cs:2775)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

### Steps to Reproduce

1.Open 3D Object Detection scene
2.Click PlayButton

### Expected Result

![nyc-boxes](https://user-images.githubusercontent.com/40350500/161684896-506e6566-198f-48bb-a454-b90044668e43.png)

### Actual Result

The camera content can be displayed on the screen, but it is not recognized.

### ZED Camera model

ZED2

### Environment

```shell
Operating System:windows 10 10.0 19043
Processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 CPUs), ~3.2GHz
Memory: 16384MB RAM
Available OS Memory: 16222MB RAM
Page File: 14467MB used, 11483MB available
Windows Dir: C:\Windows
DirectX Version: DirectX 12

Zed Sdk :ZED_SDK_Windows10_cuda11.5_v3.7.1.exe
cuda :cuda_11.5.0_496.13_win10.exe
Zed_Unity:ZED_Unity_Plugin_v3.7.1.unitypackage
```

### Anything else?

{
    "AI Models": {
        "info": [
            "MULTI CLASS DETECTION is not optimized",
            "MULTI CLASS MEDIUM DETECTION is not optimized",
            "MULTI CLASS ACCURATE DETECTION is not optimized",
            "HUMAN BODY FAST DETECTION is not optimized",
            "HUMAN BODY MEDIUM DETECTION is not optimized",
            "HUMAN BODY ACCURATE DETECTION is not optimized",
            "PERSON HEAD DETECTION is not optimized",
            "REID ASSOCIATION is not optimized",
            "NEURAL DEPTH is not optimized"
        ]
    },
    "Camera Test": {
        "InternalDevicesCount": 1,
        "ZEDCount": 1,
        "camera": {
            "Device ID": 0,
            "Firmware": 1523,
            "Init Output": "OK",
            "Model": "ZED",
            "Serial Number": 12358,
            "valid": [
                "<b>Camera: </b>ZED",
                "<b>Firmware: </b>1523"
            ]
        },
        "resolutions": {
            "HD1080@15": {
                "fps (input)": 15,
                "fps (output)": 15,
                "height (input)": 1080,
                "height (output)": 1080,
                "initialization": "OK",
                "status": true,
                "width (input)": 1920,
                "width (output)": 1920
            },
            "HD1080@30": {
                "fps (input)": 30,
                "fps (output)": 30,
                "height (input)": 1080,
                "height (output)": 1080,
                "initialization": "OK",
                "status": true,
                "width (input)": 1920,
                "width (output)": 1920
            },
            "HD2K@15": {
                "fps (input)": 15,
                "fps (output)": 15,
                "height (input)": 1242,
                "height (output)": 1242,
                "initialization": "OK",
                "status": true,
                "width (input)": 2208,
                "width (output)": 2208
            },
            "HD720@15": {
                "fps (input)": 15,
                "fps (output)": 15,
                "height (input)": 720,
                "height (output)": 720,
                "initialization": "OK",
                "status": true,
                "width (input)": 1280,
                "width (output)": 1280
            },
            "HD720@30": {
                "fps (input)": 30,
                "fps (output)": 30,
                "height (input)": 720,
                "height (output)": 720,
                "initialization": "OK",
                "status": true,
                "width (input)": 1280,
                "width (output)": 1280
            },
            "HD720@60": {
                "dropCount": 0,
                "fps (input)": 60,
                "fps (output)": 60,
                "height (input)": 720,
                "height (output)": 720,
                "imageCount": 501,
                "initialization": "OK",
                "status": true,
                "tearingCount": 0,
                "width (input)": 1280,
                "width (output)": 1280
            },
            "VGA@100": {
                "fps (input)": 100,
                "fps (output)": 79,
                "height (input)": 376,
                "height (output)": 376,
                "initialization": "OK",
                "status": true,
                "width (input)": 672,
                "width (output)": 672
            },
            "VGA@15": {
                "fps (input)": 15,
                "fps (output)": 15,
                "height (input)": 376,
                "height (output)": 376,
                "initialization": "OK",
                "status": true,
                "width (input)": 672,
                "width (output)": 672
            },
            "VGA@30": {
                "fps (input)": 30,
                "fps (output)": 30,
                "height (input)": 376,
                "height (output)": 376,
                "initialization": "OK",
                "status": true,
                "width (input)": 672,
                "width (output)": 672
            },
            "VGA@60": {
                "fps (input)": 60,
                "fps (output)": 48,
                "height (input)": 376,
                "height (output)": 376,
                "initialization": "OK",
                "status": true,
                "width (input)": 672,
                "width (output)": 672
            }
        },
        "sensors": {
        }
    },
    "Graphics Card": {
        "deviceCount": 1,
        "deviceDriverVersion": 11050,
        "devices": [
            {
                "arch": "Pascal",
                "computeCapability": "6.1",
                "cores": 1280,
                "name": "NVIDIA GeForce GTX 1060 6GB",
                "totalMemoryBytes": "6442254336",
                "totalMemoryMB": 6143.8125
            }
        ],
        "initResult": 0,
        "valid": [
            "<b>Graphics card: </b> NVIDIA GeForce GTX 1060 6GB"
        ]
    },
    "Processor": {
        "OS": "Windows 10 FallCreators",
        "avxSupported": true,
        "coreCount": "6",
        "cpu": "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz",
        "datetime": "2022-04-05 14:18:17",
        "hyperThreading": "1",
        "motherboard": "3132, LENOVO",
        "ramCapacity": "15.8425",
        "ramUsage": "0",
        "ramUsed": "7.28469",
        "threadCount": "12",
        "valid": [
            "<b>Processor: </b> Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz",
            "<b>Motherboard: </b> 3132, LENOVO"
        ]
    },
    "USB": {
        "ASMediaFound": false,
        "CorruptedFirmware": false,
        "OC_Cam_Detected": false,
        "OtherUSBDevices": [
        ],
        "USBList": [
            {
                "USB_path": "/3",
                "idProduct": "0xc52f",
                "idVendor": "0x046d"
            },
            {
                "USBMode": 3,
                "USB_path": "/20",
                "bDescriptorType": 1,
                "bDeviceProtocol": 1,
                "bLength": 18,
                "bMaxPacketSize0": 9,
                "bNumConfigurations": 1,
                "bcdDevice": "1.0",
                "bcdUSB": "3.0",
                "bcdUSBClass": 239,
                "bcdUSBSubClass": 2,
                "busNumber": 1,
                "device": "ZED",
                "iManufacturer": 1,
                "iProduct": 2,
                "iSerial": 0,
                "idProduct": "0xf582",
                "idVendor": "0x2b03"
            },
            {
                "USB_path": "/1",
                "idProduct": "0xc338",
                "idVendor": "0x046d"
            },
            {
                "USBMode": 3,
                "USB_path": "/20",
                "bDescriptorType": 1,
                "bDeviceProtocol": 1,
                "bLength": 18,
                "bMaxPacketSize0": 9,
                "bNumConfigurations": 1,
                "bcdDevice": "1.0",
                "bcdUSB": "3.0",
                "bcdUSBClass": 239,
                "bcdUSBSubClass": 2,
                "busNumber": 1,
                "device": "ZED",
                "iManufacturer": 1,
                "iProduct": 2,
                "iSerial": 0,
                "idProduct": "0xf582",
                "idVendor": "0x2b03"
            }
        ],
        "USBMode": 3,
        "ZED Camera Module Detected": 62850,
        "ZEDDetected": true,
        "captureDevices": [
        ],
        "controllers": [
            {
                "CompatibleIDs": "PCI\\VEN_8086&DEV_A36D&REV_10",
                "Description": "&\b USB xHCI �;:�6h",
                "DeviceName": "Intel(R) USB 3.1 �iU;:�6h - 1.10 (Microsoft)",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0000",
                "Location": "PCI ;� 0\u0001�\u0007 20\u0001�� 0",
                "Manufacturer": "\u001a( USB xHCI ;:�6h",
                "Name": "PCI",
                "PhysicalName": "\\Device\\NTPNP_PCI0004"
            },
            {
                "CompatibleIDs": "",
                "Description": "USB 9ƿh(USB 3.0)",
                "DeviceName": "",
                "Driver": "{36fc9e60-c465-11cf-8056-444553540000}\\0001",
                "Location": "",
                "Manufacturer": "(\u0007� USB ƿh)",
                "Name": "USB",
                "PhysicalName": "\\Device\\USBPDO-0"
            }
        ],
        "valid": [
            "<b>USB Bandwidth: </b> OK"
        ]
    },
    "ZED SDK": {
        "CUDA Toolkit version": "V11.5.50 -->located in C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5/bin/nvcc.exe",
        "CUDA loading": false,
        "CUDA_reachable": true,
        "ZED SDK Version (Diag)": "3.7.1",
        "ZED SDK Version (RT)": "3.7.1",
        "ai": {
            "checkAI": true,
            "cudaVersion": 11050,
            "cudnnCudartVersion": 11030,
            "cudnnVersion": 8201,
            "cudnnVersionExpected": 8201,
            "tensorVersion": 8201
        },
        "binFiles": [
            "cudnn64_8.dll",
            "cudnn_adv_infer64_8.dll",
            "cudnn_adv_train64_8.dll",
            "cudnn_cnn_infer64_8.dll",
            "cudnn_cnn_train64_8.dll",
            "cudnn_ops_infer64_8.dll",
            "cudnn_ops_train64_8.dll",
            "nvinfer.dll",
            "nvinfer_builder_resource.dll",
            "nvinfer_plugin.dll",
            "nvonnxparser.dll",
            "nvparsers.dll",
            "sl_ai64.dll",
            "sl_zed64.dll"
        ],
        "driverVersion": "496.13",
        "drivervDllVersion": "30.0.14.9613",
        "resourcesFiles": [
            "objects_performance_2.1.model"
        ],
        "resourcesFilesExpected": [
            "objects_performance_2.1"
        ],
        "runtimeDllVersion": 11050,
        "valid": [
            "<b>ZED SDK version:</b> 3.7.1",
            "<b>CUDA version:</b> V11.5.50"
        ]
    }
}

**Comment by obraun-sl** [comment]
Hi,
You need to optimize the model first for your graphic card. You can do it with ZED Diagnostic tool : 
For ex, to optimize multi class accurate : 
$ ZED_Diagnostic.exe -ais 2 

You can also optimize all the models in one command : 
$ ZED_Diagnostic.exe -aio 
(but it takes some time)

**Comment by AsIfPu** [comment]
> 您好， 您需要先为您的显卡优化模型。您可以使用 ZED 诊断工具来做到这一点： 例如，优化多类准确： `$ ZED_Diagnostic.exe -ais 2 `
> 
> 您还可以在一个命令中优化所有模型：（ `$ ZED_Diagnostic.exe -aio ` 但这需要一些时间）

Thank you for your reply！AI models has been loaded successfully.
But the 3D Object Detection still doesn't work.

`Object Detection failed to start. (Error: MODULE_NOT_COMPATIBLE_WITH_CAMERA )`

My camera is zed2.

**Comment by AsIfPu** [comment]
> Hi, You need to optimize the model first for your graphic card. You can do it with ZED Diagnostic tool : For ex, to optimize multi class accurate : `$ ZED_Diagnostic.exe -ais 2 `
> 
> You can also optimize all the models in one command : `$ ZED_Diagnostic.exe -aio ` (but it takes some time)

Thank you for your reply！AI models has been loaded successfully.
But the 3D Object Detection still doesn't work.

`Object Detection failed to start. (Error: MODULE_NOT_COMPATIBLE_WITH_CAMERA )`

My camera is zed2.

**Comment by obraun-sl** [comment]
From the diagnostic file, it seems you are using a ZED not a ZED2
```

"Model": "ZED",
"Serial Number": 12358,
"valid": [
"Camera: ZED",
"Firmware: 1523"
```

**Comment by AsIfPu** [comment]
> From the diagnostic file, it seems you are using a ZED not a ZED2
> 
> ```
> 
> "Model": "ZED",
> "Serial Number": 12358,
> "valid": [
> "Camera: ZED",
> "Firmware: 1523"
> ```

Um...I must have taken the wrong camera
Thank you very much for your reply
