### ISSUE TITLE
Right eye not using Neural Depth Mode in AR Pass-through

### ISSUE THREAD

**Issue by Gregory-Baker** [stereolabs/zed-unity#235]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I'm using the ZED2 in AR pass-through mode, which isn't recommended, I know, but I assume the problem would be the same for the ZED mini as well. 

I am using Neural Depth mode, which I have found to be the best by far. What I have noticed is that the Right Eye depth occlusion is significantly worse than the left eye. My suspicion is that the depth mode for the right eye is being processed using a depth mode other than Neural.

This picture shows the left and right eye depth frames in Ultra depth mode:
![depth-mode-ultra](https://user-images.githubusercontent.com/32361667/169311282-c7b74eee-01f7-4907-8078-a03cfacbbc0d.png)
Very similar, right?

This picture shows the left and right eye depth frames in (supposedly) Neural depth mode:
![depth-mode-neural](https://user-images.githubusercontent.com/32361667/169314898-2d616440-49e9-4166-9796-37bc792609a4.png)
A bit different. Notice in the right-hand image there is a lack of detail on the tall object in the left of frame, compared to the left eye.

 

### Steps to Reproduce

Run AR pass-through with neural depth mode and check out the discrepancy between depth occlusion performance in both. Or just look at the depth images in both and see if they look like they are using the same depth mode, or not.

### Expected Result

Similar depth frames and depth occlusion results in each eye.

### Actual Result

Noticeably different depth occlusion between eyes. Parts of the 'ground-plane' and other objects from my unity scene that are visible in the left eye are not showing, partially showing, or flickering in the right eye.

### ZED Camera model

ZED2

### Environment

```shell
My setup uses a ZED2 streaming from an NVIDIA Jetson AGX to a windows PC running Unity and interfacing with the VR (HTC Vive) headset. I guess the result would be the same with the ZED connected directly to the WIndows PC (running Unity) by USB, but I haven't checked. I can though, if necessary.

OS: Windows 10
ZED SDK version: 3.7.2
Unity Version: 2020.3.14
ZED-Unity plugin version: 3.7.1
GPU: Nvidia GeForce RTX 3090
```

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for reaching us out.
Indeed, in NEURAL mode, the right depth is computed with a "lighter" version of the NEURAL depth algorithm.
This choice has been made to reduce the computation time which would be significantly higher otherwise.

We are not completely against changing that in the future and adding the option to choose might be a better solution. 

Best regards,
Benjamin Vallon
