### ISSUE TITLE
Zed2I support

### ISSUE THREAD

**Issue by SabinMG** [stereolabs/zed-unity#240]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

We are looking to buy ZED 2i and would like to know the unity SDK will support ZED 2i.

**Comment by Bvallon-sl** [comment]
Hi,

Yes, the Unity plugin supports the ZED2i camera.
However, for VR/AR applications using a VR headset, it is recommended to use the ZED-mini camera instead.

Best regards,
Benjamin Vallon
