### ISSUE TITLE
Connect more then four ZED cameras - Increase number of svo playback

### ISSUE THREAD

**Issue by skagla** [stereolabs/zed-unity#245]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Currently it's not possible to connect more than 4 cameras (Camera ID: You can connect up to four ZED or ZED Mini cameras to a single PC at once. )
Would it be possible to increase this limit to 8 for svo playback?

### Use-Case

I recorded many scenes with 8 cameras on 2 PCs, and know I'm trying to play them back in one unity scene, but I'm unable to play more than 4 SVOs at the same time.

**Comment by Bvallon-sl** [comment]
Hi,

For the moment, the number of cameras is limited to 4. We initially added this limit because each ZED Camera instance required a certain number of layers.
We will look into your request and see if we can increase the maximum number of cameras.

I'll keep you informed.

Best,

**Comment by skagla** [comment]
Hi,
thanks. It would be highly appreciated if it would be possible to increase the number of cameras to 8. That would really help to advance our project and the research in volumetric video.
