### ISSUE TITLE
Marshal.Copy(ZEDMat.MatPtr, byte[] t, 0, length) crashes?

### ISSUE THREAD

**Issue by axing0805091** [stereolabs/zed-unity#25]
`using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using UnityEngine;

public class textureManaging : MonoBehaviour {
    public GameObject ZED_Rig_Stereo;
    sl.ZEDMat slMat = new sl.ZEDMat(1280, 720, sl.ZEDMat.MAT_TYPE.MAT_8U_C4, sl.ZEDMat.MEM.MEM_CPU);
    ZEDManager zedmanager;
    byte[] t = new byte[1280 * 720 * 4];
    void Awake()
    {
        zedmanager = ZED_Rig_Stereo.GetComponent<ZEDManager>();
    }
    // Update is called once per frame
    void Update()
    {

        zedmanager.zedCamera.RetrieveImage(slMat, sl.VIEW.LEFT, sl.ZEDMat.MEM.MEM_CPU, slMat.GetResolution());
        Debug.Log(slMat.GetChannels());
        Debug.Log(slMat.GetInfos());
        Marshal.Copy(slMat._matInternalPtr, t, 0, 1280 * 720* 4);
    }
}`

I put a plane in the scene attached with the above script. And I put a ZED_Rig_Stereo prefab in the scene and attach it to the "public GameObject ZED_Rig_Stereo".  When I comment the last line code "Marshal.Copy()", it works well. When I uncomment it, Unity3D will shut down automatically. How can I transform ZEDMat into byte[]? I'm a beginner to c#, thanks for answering.

**Comment by axing0805091** [comment]
By the way, I changed ZEDMat._matInternalPtr to public.  "Marshal.Copy(slMat.MatPtr, t, 0, 1280*720*4)" also has the same error.

**Comment by axing0805091** [comment]
I want to transform ZEDMat into OpenCvSharp Mat to detect aruco markers, can anyone help me ?

**Comment by dogod621** [comment]
I think may be _matInternalPtr is pont to ZEDMat object,
It is not pont to data,
it only contains width, height, type, dataPtr... etc informations.

Maybe you should use ZEDMate's GetPtr:

public System.IntPtr GetPtr(MEM mem = MEM.MEM_CPU)
{
            return dllz_mat_get_ptr(_matInternalPtr, (int)mem);
}

Then copy from this pointer (point to data)
