### ISSUE TITLE
ZED Unity plugin crashes

### ISSUE THREAD

**Issue by mikeszabi** [stereolabs/zed-unity#254]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Trying to reproduce body tracking example with UNITY's ZED plugin. It crashes right after starting to run the project. I tries Zed Mini and ZED 2i. I attached editor.log from unity.

### Steps to Reproduce

1.NEW Unity URP project
2.Import ZED plugin
3.Add ZED_Rig_Mono prefab
4.Run Unity project
...

### Expected Result

ZED Unity plugin runs fine as stated in examples (https://www.stereolabs.com/docs/unity/body-tracking/)

### Actual Result

Obtained 4 stack frames.
#0  0x00555a6c29f97c in burst_signal_handler(int, siginfo_t*, void*)
#1  0x007fd18d442520 in __sigaction
#2  0x007fcefbc60a5f in sl_set_roi_for_aec_agc
#3  0x0000004008b19d in (wrapper managed-to-native) sl.ZEDCamera:dllz_set_roi_for_aec_agc (int,int,sl.Rect,bool)
[Editor.log](https://github.com/stereolabs/zed-unity/files/11478949/Editor.log)

### ZED Camera model

ZED2i

### Environment

```shell
Ubuntu 22.04
AMD Ryzen 5 1500X Quad-Core Processor
NVIDIA Driver Version: 510.108.03   CUDA Version: 11.6
ZED_SDK_Ubuntu22_cuda11.7_v3.8.2.zstd.run
Zed_Unity_Plugin_v4.0.2
```

### Anything else?

Tested with ZED mini and ZED 2i - with same result

**Comment by BlueprintBen** [comment]
Commenting out that line doesn't resolve the crash issue for me.
