### ISSUE TITLE
`ScriptableRenderContext` could be not found

### ISSUE THREAD

**Issue by waltejon** [stereolabs/zed-unity#257]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I have an issue while importing the Unity plugin.

### Steps to Reproduce

1. Create new 3D (URP) project
2. Assets > Import New Package > Custom Package ... > Unity Plugin 4.0.3
3. Project Settings > XR Plugin Management > Install XR Plugin Management System

### Expected Result

I expected to be able to import the Unity plugin without issues.
Furthermore, after the import, I expected be able to run a ZED example scene, e.g., an example scene for the body tracking.

### Actual Result

The Unity console shows the following error:

`Assets\ZED\SDK\Helpers\Scripts\MR\ZEDMixedRealityPlugin.cs(662,32): error CS0246: The type or namespace name 'ScriptableRenderContext' could not be found (are you missing a using directive or an assembly reference?)`

![image](https://github.com/stereolabs/zed-unity/assets/44841727/0c8dddaf-41ae-40eb-b4eb-69cad74724e0)

![image](https://github.com/stereolabs/zed-unity/assets/44841727/f908ac3d-2b42-4e41-8fa1-4b6ed6437519)

![image](https://github.com/stereolabs/zed-unity/assets/44841727/e17cb8ec-f4f3-4723-a7a3-423dcc62769f)

### ZED Camera model

ZED2

### Environment

```shell
Windows 10
Intel i9
Nvidia RTX 3090
ZED SDK 4.0.3
ZED Unity Plugin 4.0.3
```

**Comment by waltejon** [comment]
I also followed the „How to get started“ steps from here: https://www.stereolabs.com/docs/unity/.

Maybe not relevant in this context, but the context menu in my Unity 2022.3 editor are different to the steps above - for example, to create such a universal rendering pipeline asset

**Comment by SLJLMacarit** [comment]
Hi @waltejon, 

I think this post on the forum should help: [Unity ScriptableRenderContext Error when trying example scene](https://community.stereolabs.com/t/unity-scriptablerendercontext-error-when-trying-example-scene/2763/2?u=jplou)

Add `using UnityEngine.Rendering;` at the beginning of `Assets\ZED\SDK\Helpers\Scripts\MR\ZEDMixedRealityPlugin.cs`. We'll soon release a fix to this oversight.

Best,
Jean-Loup

**Comment by waltejon** [comment]
@SLJLMacarit: Yes, this hint solved my issue. Thank you!
