### ISSUE TITLE
No ZEDCamera.unitypackage

### ISSUE THREAD

**Issue by zacharyyamaoka** [stereolabs/zed-unity#264]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

In the most recent release of the unity package there is no ZEDCamera.unitypackage file to download

### Steps to Reproduce

1.
2.
3.
...
n/a

### Expected Result

n/a

### Actual Result

n/a

### ZED Camera model

ZED

### Environment

```shell
n/a
```

**Comment by Bvallon-sl** [comment]
Hi,

Indeed, the unity package is missing. 

We will add it shortly.

Thanks for the feedback.

Best regards.
Benjamin Vallon
