### ISSUE TITLE
Missing scripts ( prefabs missing scripts) - Body tracking module 

### ISSUE THREAD

**Issue by samphilips** [stereolabs/zed-unity#266]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I was trying to use the body tracking module, and was following the steps given in the ZED Unity documentation https://www.stereolabs.com/docs/unity/   , was facing the error that the prefabs are missing scripts, and the mono and stereo camera are missing scripts, images attached, I am currently using windows 11, with unity 2022.x , please advice what is the issue 

<img width="604" alt="image" src="https://github.com/stereolabs/zed-unity/assets/139512584/3b316ef4-7321-4ba1-b3bf-d50b9fa08a5f">

![image](https://github.com/stereolabs/zed-unity/assets/139512584/51311c30-4724-452c-a22a-082ae58877f7)

### Steps to Reproduce

1. import asset - unity zed plugin 
2. add camera - mono or stereo 

### Expected Result

1. get the zed manager script 

### Actual Result

![image](https://github.com/stereolabs/zed-unity/assets/139512584/32b25b9e-5e53-4d1b-ae0d-62875777e7ad)

### ZED Camera model

ZED2

### Environment

```shell
Windows 11 
gpu - nvidia RTX 3060 X 2 
CUDA Version : 12.1
ZED SDK 4.0 
Unity plugin : 4.0.5
Unity version 2022.x
```

**Comment by SLJLMacarit** [comment]
Hi @samphilips,

Sorry for the delay.
Can you try adding the XR Management package from Project Settings -> XR Plugin Management?

**Comment by samphilips** [comment]
> Hi @samphilips,
> 
> Sorry for the delay. Can you try adding the XR Management package from Project Settings -> XR Plugin Management?
> 
> Edit: Just saw your other comment on the crash with 4.0.6. I'll try some things and be back.

Thank you for your response, I was able to downgrade my system to windows 10 and try and it works for now, I am facing another error of camera not being found in the unity zed, set up, however, it works in the ZED SDK, Image attached but the unity isn't able to detect the camera, I have followed all the steps given in this documentation  https://www.stereolabs.com/docs/unity/body-tracking/#run-the-scene 

![image](https://github.com/stereolabs/zed-unity/assets/139512584/b50326c4-5d6b-4b9c-b5cb-3d6ab830e2b5)

![image](https://github.com/stereolabs/zed-unity/assets/139512584/73923279-b66c-4d56-8301-6e2485eeb622)

**Comment by samphilips** [comment]
> > Hi @samphilips,
> > Sorry for the delay. Can you try adding the XR Management package from Project Settings -> XR Plugin Management?
> > Edit: Just saw your other comment on the crash with 4.0.6. I'll try some things and be back.
> 
> Thank you for your response @SLJLMacarit , I was able to downgrade my system to windows 10 and try and it works for now, I am facing another error of camera not being found in the unity zed, set up, however, it works in the ZED SDK, Image attached but the unity isn't able to detect the camera, I have followed all the steps given in this documentation https://www.stereolabs.com/docs/unity/body-tracking/#run-the-scene
> 
> ![image](https://user-images.githubusercontent.com/139512584/261689738-b50326c4-5d6b-4b9c-b5cb-3d6ab830e2b5.png)
> 
> ![image](https://user-images.githubusercontent.com/139512584/261690333-73923279-b66c-4d56-8301-6e2485eeb622.png

to give a broader perspective, this is how my unity screen looks like 
![image](https://github.com/stereolabs/zed-unity/assets/139512584/a9b9ccdb-6f48-40a2-99be-7e3d5eb89c9c)

**Comment by samphilips** [comment]
hi @SLJLMacarit could you please help me with this, what can be done to make this work, thank you

**Comment by SLJLMacarit** [comment]
I'm happy it's solved by upgrading, but I'm sad because it didn't used to be necessary.
I logged this issue internally, we'll investigate it more in-depth.
