### ISSUE TITLE
Crash with Zed 2.6 / Unity

### ISSUE THREAD

**Issue by LeeVermeulen** [stereolabs/zed-unity#27]
I installed Zed v2.6 SDK + the latest Unity 2.6 SDK and am getting a crash on startup.
I installed the latest version in a attempt to stop the Zed camera from freezing (VR would still be active, but the display would freeze in space and no longer update)

There is a error that 'ZED (Init) >> ERROR: Executable was designed for SDK v2.5.0 / installed v2.6.0' - when v2.6 SDK is definitely installed.

Crash log on starting up:

> [VRDevice] Successfully created device OpenVR.
> Reloading assemblies for play mode.
> Begin MonoManager ReloadAssembly
> Refreshing native plugins compatible for Editor in 2.30 ms, found 6 plugins.
> Preloading 2 native plugins for Editor in 0.20 ms.
> Mono: successfully reloaded assembly
> - Completed reload, in  1.028 seconds
> Initializing Unity.PackageManager (PackageManager) v2017.4.11 for Unity v2017.4.11f1
> Registering platform support modules:
> Registered platform support modules in: 0.0398086s.
> Native extension for WindowsStandalone target not found
> Load scene 'Temp/__Backupscenes/0.backup' time: 0.436622 ms 
> Refreshing native plugins compatible for Editor in 0.60 ms, found 6 plugins.
> ZED (Init) >> ERROR: Executable was designed for SDK v2.5.0 / installed v2.6.0
> 
> Connected to lighthouse:LHR-1B5DD5AB
> UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> SteamVR:.ctor() (at Assets\SteamVR\Scripts\SteamVR.cs:253)
> SteamVR:CreateInstance() (at Assets\SteamVR\Scripts\SteamVR.cs:97)
> SteamVR:get_instance() (at Assets\SteamVR\Scripts\SteamVR.cs:48)
> SteamVR_Render:OnEnable() (at Assets\SteamVR\Scripts\SteamVR_Render.cs:287)
> UnityEngine.GameObject:Internal_AddComponentWithType(Type)
> UnityEngine.GameObject:AddComponent(Type) (at C:\buildslave\unity\build\artifacts\generated\common\runtime\GameObjectBindings.gen.cs:382)
> UnityEngine.GameObject:AddComponent() (at C:\buildslave\unity\build\artifacts\generated\common\runtime\GameObjectBindings.gen.cs:387)
> SteamVR_Render:get_instance() (at Assets\SteamVR\Scripts\SteamVR_Render.cs:33)
> ZEDControllerTracker:OnEnable() (at Assets\ZED\SDK\Helpers\Scripts\Interactions\ZEDControllerTracker.cs:317)
>  
> (Filename: Assets/SteamVR/Scripts/SteamVR.cs Line: 253)

**Comment by obraun-sl** [comment]
When you update the plugin through the repo, did you make sure that Unity was closed ? 
Sometimes, the plugin dll (sl_unitywrapper.dll) cannot be updated if Unity is open and has already played a scene.

From the issue, it seems that the plugin dll is still on 2.5 build.

**Comment by LeeVermeulen** [comment]
that was it! Thanks for that
