### ISSUE TITLE
replacing bounding boxes of custom objects with prefabs/models 

### ISSUE THREAD

**Issue by samphilips** [stereolabs/zed-unity#271]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Could you guide me how to replace prefabs for replacing 3d boxes around differernt objects with different prefabs, 
I have already done that for single object, by changing the 3D bounding box prefab with custom object  prefab of single object- bag at the moment, 
![image](https://github.com/stereolabs/zed-unity/assets/139512584/8fbf885d-7bb3-4e28-9798-add18bdb95a9)
however I want to add  multiple prefab
for example, if a chair is detected using YOLO, I want the 3bouding box to be replaced with chair prefab, and if bag is detected then I want it to be replaced with chair prefab, 
I am attaching the image of what I have achieved so far, changing bag detection, right now I have filtered only bag to be detected, 
![image](https://github.com/stereolabs/zed-unity/assets/139512584/5dfd5227-c6ac-4b70-b1dd-389fcfd73fa6)

real world 
![image](https://github.com/stereolabs/zed-unity/assets/139512584/520a8673-feeb-418f-ab94-c6d00229d8b4)

**Comment by SLJLMacarit** [comment]
Hi @samphilips,
You'd have to make a script of your own or extend `ZED3DObjectVisualizer.cs`. You can take a look at [the `Visualize3DBoundingBox` function](https://github.com/stereolabs/zed-unity/blob/264d44b8be9c7205184982a9fa169c9be5695638/ZEDCamera/Assets/ZED/Examples/Object%20Detection/Scripts/ZED3DObjectVisualizer.cs#L207) to see how the 3D boxes are managed and when the prefab is called and used.
Then you'd add your own prefabs in the script variables and test the label or sublabel on the detected objects to know which prefab to spawn.
