### ISSUE TITLE
Direct3D12 not supported

### ISSUE THREAD

**Issue by keli95566** [stereolabs/zed-unity#273]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

All current SDKs do not support direct3D12 or Vulkan, can't use the ZED sdk with projects with D3D12 or Vulkan requirements. When will this graphics backend be supported?

**Comment by SLJLMacarit** [comment]
Hi,

It is in our backlog but it's not requested much, so we didn't plan to implement it short-term.
We'll investigate the changes needed and evaluate the priority again.

**Comment by keli95566** [comment]
Hi there, is the native plugin of ZED Unity based on the ZED C++ implementation? Would it be possible in the future to open source the native-plugin C++ project as well? This makes it easier to extend and implement any features on top of the existing plugins.
