### ISSUE TITLE
The ZED plugin cannot be loaded

### ISSUE THREAD

**Issue by Nikolatesla-lj** [stereolabs/zed-unity#284]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

![1234567](https://github.com/stereolabs/zed-unity/assets/34672324/439eb693-c321-422d-862b-c67caa75d463)
![123456](https://github.com/stereolabs/zed-unity/assets/34672324/4b7be2d2-f7ea-4619-afb5-06c3ce3e215d)
![12334](https://github.com/stereolabs/zed-unity/assets/34672324/752d0fb0-ae79-4937-9371-ab1f882a10d8)

### Steps to Reproduce

Follow the steps to install the file "Zed_Unity_Plugin_v4.0.7.unitypackage", the following error occurs

### Expected Result

unity3D is working properly

### Actual Result

DllNotFoundException
UnityEngine.Debug:Log (object)
sl.ZEDCamera:CheckPlugin () (at Assets/ZED/SDK/NativeInterface/ZEDCamera.cs:920)
ZEDPluginInspector:UpdateWnd () (at Assets/ZED/Editor/Scripts/ZEDPluginInspector.cs:159)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /home/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:381)
————————————————————————————————-——————————

The ZED plugin cannot be loaded. 
 Please check that you have ZED SDK v4.0 installed

 If the problem persists, please contact our support team at support@stereolabs.com

UnityEngine.Debug:LogError (object)
sl.ZEDCamera:CheckPlugin () (at Assets/ZED/SDK/NativeInterface/ZEDCamera.cs:921)
ZEDPluginInspector:UpdateWnd () (at Assets/ZED/Editor/Scripts/ZEDPluginInspector.cs:159)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /home/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:381)

### ZED Camera model

ZED2i

### Environment

```shell
OS：Ubuntu 22.04
unity 3D：2022.3.21.f1
ZED SDK： 4.0.8
CUDA:12.1

Zed_Unity_Plugin_v4.0.7
```

**Comment by keith-lackey-steamroller-tech** [comment]
I'm running into this same exact issue. how do i resolve?

**Comment by ethanguo770** [comment]
https://community.stereolabs.com/t/unity-error-zed-sdk-is-not-installed-or-needs-to-be-updated/7218/3
