### ISSUE TITLE
ZED SDK and OpenCvForUnity integration not working

### ISSUE THREAD

**Issue by lawl2** [stereolabs/zed-unity#292]
![XILAB-D38 - Remote Desktop Connection 16_07_2024 11_41_31](https://github.com/user-attachments/assets/ed758a53-9f65-4303-8722-e1b5df18c363)
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hi,
I'm working on a project trying to integrate ZED SDK in Unity and OpenCV for Unity. I'm using OpenCV for Unity (not free version) for a previous project now I would like to integrate ZED cameras in the project. I have installed, using Git, the ZED SDK in Unity but when I try to reproduce one of the simplest examples in your docs (for Object Detection) I have many errors in the Unity console like "The type or namespace name 'OpenCVForUnity' could not be found (are you missing a using directive or an assembly reference?)". I've also tried many solutions in your forum like suggested in https://community.stereolabs.com/t/problem-running-zed-mini-with-opencv-for-unity-sample/4091 or https://community.stereolabs.com/t/zed-customdetection-cs-not-working-with-opencvforunity-plugin/4829/5 but still not working
How to solve it?
Thanks for your attention.

### Steps to Reproduce

1. Importing OpenCvForUnity
2. Installing CUDA and ZED SDK
3. Installing ZED SDK in Unity

### Expected Result

Errors not showing in Unity console and OpenCvForUnity library correctly seen and found

### Actual Result

Many errors involving Object Detection script and many others not able to see OpenCvForUnity

### ZED Camera model

ZED2i

### Environment

```shell
OS: Windows 10
CPU: Intel
GPU: Nvidia 1080Ti
ZED SDK version: v4.1.1
Unity v2022.3.20f1
OpenCV for Unity v1.7.1
```

**Comment by zach-dpt** [comment]
I'm running in the same issue. Were you able to fix it?
