### ISSUE TITLE
OpenCV for Unty

### ISSUE THREAD

**Issue by SevenAntares** [stereolabs/zed-unity#38]
Hi, I'm trying to integrate OpenCV for Unity 
https://assetstore.unity.com/packages/tools/integration/opencv-for-unity-21088

I remove the Main Camera and import "ZED_Rig_Mono" but I can not get it to work. Is there any way to create a compatibility with this plugin? Thank you

**Comment by bernardbme** [comment]
I also have the same question. I am trying to run a marker-based AR task with the help of the zed-mini and htc vive pro hmd. How to take the camera image from zed SDK and process it with openCV for unity plugin? I have tried to use the texture2D textureEye from the ZedRenderingPlane.cs. It is not working. I also tried to extract the ZEDMat and reconstruct the 2d texture. But, this increases the motion latency.

**Comment by Sakuyal** [comment]
Anyone able to get the ZED to work with this plugin?

**Comment by jernejp21** [comment]
Have you tried this [OpenCV ArUco Detection](https://github.com/stereolabs/zed-unity/tree/master/ZEDCamera/Assets/ZED/Examples/OpenCV%20ArUco%20Detection) example? It worked great for me. I was also able to modify the program so that I can track multiple markers on single object.
