### ISSUE TITLE
Support for HDR pipeline

### ISSUE THREAD

**Issue by otite** [stereolabs/zed-unity#50]
Hi, it would be awesome if the unity plugin could support the HDR render pipeline of unity.
G.

**Comment by ckorris** [comment]
Thanks for the suggestion. A few people have asked for this, though we've researched it and it will be a long and complicated process to add full HDRP support. It _is_ on the To Do list, but as the vast majority of users are using Standard, please note it'll still be a little while as we've prioritized other features.

**Comment by djesko1** [comment]
Was going to ask this also. It will be essential for my project going forward.

**Comment by flaming910** [comment]
Could you maybe give some guidance on what could be changed to use the ZED with HDRP?

**Comment by peterfiftyfour** [comment]
Hey all, any update on this? I managed to get some stuff partially working. The only issue was in LookAtCameraPartialAxis where RenderPipeline.beginCameraRendering += LookAtCamera; should be RenderPipelineManager.beginCameraRendering - would love to use some fancy vfx stuff! Cheers

**Comment by davidezhang** [comment]
Would love to hear any updates as well! @peterfiftyfour when I changed it to RenderPipelineManager.beginCameraRendering, there is this error: No overload for 'LookAtCamera' matches delegate 'Action<ScriptableRenderContext, Camera>'. Would appreciate any pointers!
