### ISSUE TITLE
Microsoft Surface

### ISSUE THREAD

**Issue by dommy1C** [stereolabs/zed-unity#52]
Hi

Is this supported on Microsoft Surface?

I m trying to PInvoke sl_unitywrapper.dll from C# app but get DLL not found.  I load this dll into Dependency Walker bu I get errors saying Modules with different CPU types were found.
Am i flogging a 'dead horse' or is they something I can try?

Thanks

**Comment by obraun-sl** [comment]
Hi,
The plugin uses the ZED SDK which is only compatible with NVIDIA GPU. Surface is not supported then.
