### ISSUE TITLE
SpacialMapping Compiler error in Unity 5.5

### ISSUE THREAD

**Issue by BlueprintBen** [stereolabs/zed-unity#6]
I get a compiler error on import coming from ZED/Examples/SpacialMapping/NavMeshSurface.cs:208 which references a missing class NavMeshBuildSource. It looks like this is a 5.6+ class?

![zed-navmeshsurface](https://user-images.githubusercontent.com/26749774/33030039-12874aae-cdcf-11e7-8464-9157a5350c4b.PNG)

**Comment by nesnes** [comment]
Unity introduced the generation of NavMesh at runtime in 5.6. The minimum required version for the plugin is Unity 5.6.
