### ISSUE TITLE
ZED_Spatial_Mapping missing script

### ISSUE THREAD

**Issue by alicehaupais** [stereolabs/zed-unity#60]
Hello,

I would like to report a new issue regarding the new version v2.8 of the ZED SDK.

I wanted to do the tutorial about Spatial Mapping : https://www.stereolabs.com/docs/unity/spatial-mapping-unity/

However, the prefab mentionned ZED_Spatial_Mapping is missing a script : ZEDSpatialMappingManager.cs. I looked for another script and I found ZEDSpatialMapping.cs but this one contains compilation errors.

![ZED_Spatial_Mapping](https://user-images.githubusercontent.com/48716381/57442171-afdb2880-724b-11e9-9726-3bde8cdbfd90.png)

![ScriptErrors](https://user-images.githubusercontent.com/48716381/57442557-8b338080-724c-11e9-8caa-4577b3441cce.png)

I tried also to run the tutorial 5 - Spatial Mapping but I have also an execution error.
![tutorialError](https://user-images.githubusercontent.com/48716381/57442745-e6657300-724c-11e9-8e2a-126d7f78985f.png)

Could you tell me if there is something new with the setup of the Spatial Mapping Feature ?

Thank you for your answer !

**Comment by alicehaupais** [comment]
I successfully managed to make the Spatial Mapping script worked !

The class was not deriving from MonoBehaviour ... (script contains also this mistake in the StereoLabs git ....)

Start Spatial Mapping is now working but is not able to record anything ...

**Comment by obraun-sl** [comment]
Please note that the spatial mapping module is now directly in ZEDManager (ie ZED_Rig_Mono or Stereo prefab) and it's not a standalone module. 
Basically you just need to remove the spatial mapping prefab and replace with a ZED Rig prefab.

Take a look at the spatial mapping scene.

**Comment by alicehaupais** [comment]
Yes I managed to make the spatial mapping work from Unity. It may be time to update the tutorials ....
