### ISSUE TITLE
Compiler Error in ZEDTextureOverlay in Unity 5.5

### ISSUE THREAD

**Issue by BlueprintBen** [stereolabs/zed-unity#7]
There's a compiler error from ZED\SDK\Helpers\Scripts\Display\ZEDTextureOverlay.cs:535 where the script references camera.allowHDR. This field is called camera.hdr in Unity 5.5 and was only changed in 5.6.

**Comment by nesnes** [comment]
Same as the other issue, the minimum required version to use the plugin is Unity 5.6. 
You can check the requirements part of the documentation: https://www.stereolabs.com/documentation/mixed-reality/unity/getting-started.html#requirements
