### ISSUE TITLE
[Feature Request] Repository structure as "Unity Package"

### ISSUE THREAD

**Issue by stef-t** [stereolabs/zed-unity#74]
#### Description 
It would be nice if the ZED-Unity repository's structure would have a layout as described by Unity [in this post](https://docs.unity3d.com/Manual/cus-layout.html). By implementing this project structure one could add the ZED-Unity plugin as Unity-Package via the Package Manager.

#### Possible Worflow and Integration in a Unity Project
Other Unity related GitHub projects e.g. even feature a specific _upm_ branch in their repositories as seen [here](https://github.com/mob-sakai/UpmGitExtension/tree/upm). Note that this _upm_ branch is a [subtree of the _master_ branch](https://github.com/mob-sakai/UpmGitExtension/tree/master/Packages/UpmGitExtension). 
Unity-Packages require a `package.json` in the root directory to be recognized as Unity-Package by the Unity-Editor, that is why the git subtree command is well suited to be able to fit these requirements. Following how the git worflow might look like:
`git subtree split --prefix Assets/ZED/ --branch upm && git push origin upm`

Versioning could be handled via git tags which is very well integrated into the Unity-Package-Manager ecosytem. New releases would result in a new push to the _upm_ branch which would then get a version specific tag.

Following is an example of how a ZED-Unity package dependency for the Unity-Package-Manager might look like: 
```
 {
  "dependencies": {
    "com.stereolabs.zed-unity": "https://github.com/stereolabs/zed-unity.git#2.8.0",
    ...
  },
}
```

Note that [Assembly-Definitions](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) work very well in conjuntion with this project layout.

#### Further Reading
* [https://docs.unity3d.com/Manual/CustomPackages.html](https://docs.unity3d.com/Manual/CustomPackages.html)
* [https://docs.unity3d.com/Manual/cus-asmdef.html](https://docs.unity3d.com/Manual/cus-asmdef.html)

**Comment by ckorris** [comment]
Thank you for the suggestion and the details for implementing it. I've logged it in our internal workflow and gave it my support. It's a good suggestion and shouldn't be hard to try out.
