### ISSUE TITLE
Unity，Darkroom or SpatialMapping 's game view is black

### ISSUE THREAD

**Issue by 478161648** [stereolabs/zed-unity#81]
Hi, when i run the Darkroom or the spatialMapping,the scene view is normal, but ,the game view is black.
I noticed the Left_eye and the Right_eye camera's depth is all -1.So, I set the left_eye camera's depth 0,and the game view is back to the normal. 
Is this the right way to adjust? 
My unity is 5.6.1.

**Comment by 478161648** [comment]
and the sdk is the 2.8.3

**Comment by ckorris** [comment]
Yes, if you set the right eye camera to -1, that should fix the issue. In fact, I want to say that this is the default value in the prefab. If you create a new scene and drag+drop the ZED_Rig_Stereo prefab into the scene, do you have the same issue?
