### ISSUE TITLE
Is Your ZED SDK 2.8.3 do not support CUDA 10.2？

### ISSUE THREAD

**Issue by wsakobe** [stereolabs/zed-unity#93]

**Comment by ckorris** [comment]
I'm afraid it doesn't support CUDA 10.2 or 10.1. I recommend CUDA 10.0. You can download it here: https://developer.nvidia.com/cuda-10.0-download-archive

**Comment by obraun-sl** [comment]
2.8.5 does now support cuda 10.2
Download here : https://www.stereolabs.com/developers/release/2.8/
